//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.10 at 08:32:26 PM CST
//

package com.jumbo.webservice.outsourcingWH;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="opCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"opCode", "errorCode", "errorMsg", "result"})
@XmlRootElement(name = "bhSyncResponse")
public class BhSyncResponse implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7594621445957194556L;
    @XmlElement(required = true)
    protected String opCode = "";
    @XmlElement(required = true)
    protected String errorCode = "";
    @XmlElement(required = true)
    protected String errorMsg = "";
    @XmlElement(required = true)
    protected String result = "";

    /**
     * Gets the value of the opCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setResult(String value) {
        this.result = value;
    }

}
