//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.11 at 02:25:09 ���� CST
//

package com.jumbo.webservice.outsourcingWH;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="opCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secretKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cmpType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"opCode", "secretKey", "encType", "source", "cmpType", "callDate", "payload"})
@XmlRootElement(name = "bhSyncRequest")
public class BhSyncRequest implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6662043576610843417L;
    @XmlElement(required = true)
    protected String opCode;
    @XmlElement(required = true)
    protected String secretKey;
    @XmlElement(required = true)
    protected String encType;
    @XmlElement(required = true)
    protected String source;
    @XmlElement(required = true)
    protected String cmpType;
    @XmlElement(required = true)
    protected String callDate;
    @XmlElement(required = true)
    protected String payload;

    /**
     * Gets the value of the opCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * Sets the value of the opCode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOpCode(String value) {
        this.opCode = value;
    }

    /**
     * Gets the value of the secretKey property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * Sets the value of the secretKey property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSecretKey(String value) {
        this.secretKey = value;
    }

    /**
     * Gets the value of the encType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEncType() {
        return encType;
    }

    /**
     * Sets the value of the encType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEncType(String value) {
        this.encType = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the cmpType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCmpType() {
        return cmpType;
    }

    /**
     * Sets the value of the cmpType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCmpType(String value) {
        this.cmpType = value;
    }

    /**
     * Gets the value of the callDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCallDate() {
        return callDate;
    }

    /**
     * Sets the value of the callDate property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCallDate(String value) {
        this.callDate = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPayload(String value) {
        this.payload = value;
    }

}
