package com.jumbo.webservice.pda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.jumbo.webservice.base.AuthenticationFailedException;
import com.jumbo.webservice.pda.executeOrder.ExecuteOrderRequest;
import com.jumbo.webservice.pda.executeOrder.ExecuteOrderResponse;
import com.jumbo.webservice.pda.getInboundData.GetInboundDataRequest;
import com.jumbo.webservice.pda.getInboundData.GetInboundDataResponse;
import com.jumbo.webservice.pda.getInboundOnShelves.GetInboundOnShelvesRequest;
import com.jumbo.webservice.pda.getInboundOnShelves.GetInboundOnShelvesResponse;
import com.jumbo.webservice.pda.getInventory.GetInventoryRequest;
import com.jumbo.webservice.pda.getInventory.GetInventoryResponse;
import com.jumbo.webservice.pda.getInventoryCheck.GetInventoryCheckRequest;
import com.jumbo.webservice.pda.getInventoryCheck.GetInventoryCheckResponse;
import com.jumbo.webservice.pda.getLibraryMovement.GetLibraryMovementRequest;
import com.jumbo.webservice.pda.getLibraryMovement.GetLibraryMovementResponse;
import com.jumbo.webservice.pda.getPickingData.GetPickingDataRequest;
import com.jumbo.webservice.pda.getPickingData.GetPickingDataResponse;
import com.jumbo.webservice.pda.getReturnOrder.GetReturnOrderRequest;
import com.jumbo.webservice.pda.getReturnOrder.GetReturnOrderResponse;
import com.jumbo.webservice.pda.getSku.GetSkuRequest;
import com.jumbo.webservice.pda.getSku.GetSkuResponse;
import com.jumbo.webservice.pda.getTransNo.GetTransNoRequest;
import com.jumbo.webservice.pda.getTransNo.GetTransNoResponse;
import com.jumbo.webservice.pda.getWarehouses.GetWarehousesRequest;
import com.jumbo.webservice.pda.getWarehouses.GetWarehousesResponse;
import com.jumbo.webservice.pda.login.LoginRequest;
import com.jumbo.webservice.pda.login.LoginResponse;
import com.jumbo.webservice.pda.uploadHandOverList.UploadHandOverListRequest;
import com.jumbo.webservice.pda.uploadHandOverList.UploadHandOverListResponse;
import com.jumbo.webservice.pda.uploadInboundOnShelves.UploadInboundOnShelvesRequest;
import com.jumbo.webservice.pda.uploadInboundOnShelves.UploadInboundOnShelvesResponse;
import com.jumbo.webservice.pda.uploadInboundReceive.UploadInboundReceiveRequest;
import com.jumbo.webservice.pda.uploadInboundReceive.UploadInboundReceiveResponse;
import com.jumbo.webservice.pda.uploadInitiativeMoveInbound.UploadInitiativeMoveInboundRequest;
import com.jumbo.webservice.pda.uploadInitiativeMoveInbound.UploadInitiativeMoveInboundResponse;
import com.jumbo.webservice.pda.uploadInitiativeMoveOutbound.UploadInitiativeMoveOutboundRequest;
import com.jumbo.webservice.pda.uploadInitiativeMoveOutbound.UploadInitiativeMoveOutboundResponse;
import com.jumbo.webservice.pda.uploadInventoryCheck.UploadInventoryCheckRequest;
import com.jumbo.webservice.pda.uploadInventoryCheck.UploadInventoryCheckResponse;
import com.jumbo.webservice.pda.uploadLibraryMovement.UploadLibraryMovementRequest;
import com.jumbo.webservice.pda.uploadLibraryMovement.UploadLibraryMovementResponse;
import com.jumbo.webservice.pda.uploadPickingOutbound.UploadPickingOutboundRequest;
import com.jumbo.webservice.pda.uploadPickingOutbound.UploadPickingOutboundResponse;
import com.jumbo.webservice.pda.uploadReturnOrder.UploadReturnOrderRequest;
import com.jumbo.webservice.pda.uploadReturnOrder.UploadReturnOrderResponse;

/**
 * This class was generated by Apache CXF 2.7.4 2013-04-19T13:40:34.981+08:00 Generated source
 * version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.jumbo.com/pda/", name = "PdaService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PdaService {

    @WebResult(name = "uploadInitiativeMoveOutboundResponse", targetNamespace = "", partName = "uploadInitiativeMoveOutboundResponse")
    @WebMethod
    public UploadInitiativeMoveOutboundResponse uploadInitiativeMoveOutbound(
            @WebParam(partName = "uploadInitiativeMoveOutboundRequest", name = "uploadInitiativeMoveOutboundRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadInitiativeMoveOutboundRequest uploadInitiativeMoveOutboundRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadInitiativeMoveInboundResponse", targetNamespace = "", partName = "uploadInitiativeMoveInboundResponse")
    @WebMethod
    public UploadInitiativeMoveInboundResponse uploadInitiativeMoveInbound(
            @WebParam(partName = "uploadInitiativeMoveInboundRequest", name = "uploadInitiativeMoveInboundRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadInitiativeMoveInboundRequest uploadInitiativeMoveInboundRequest)
            throws AuthenticationFailedException;


    @WebResult(name = "uploadReturnOrderResponse", targetNamespace = "", partName = "uploadReturnOrderResponse")
    @WebMethod
    public UploadReturnOrderResponse uploadReturnOrder(@WebParam(partName = "uploadReturnOrderRequest", name = "uploadReturnOrderRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadReturnOrderRequest uploadReturnOrderRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadInventoryCheckResponse", targetNamespace = "", partName = "uploadInventoryCheckResponse")
    @WebMethod
    public UploadInventoryCheckResponse uploadInventoryCheck(
            @WebParam(partName = "uploadInventoryCheckRequest", name = "uploadInventoryCheckRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadInventoryCheckRequest uploadInventoryCheckRequest) throws AuthenticationFailedException;

    @WebResult(name = "uploadPickingOutboundResponse", targetNamespace = "", partName = "uploadPickingOutboundResponse")
    @WebMethod
    public UploadPickingOutboundResponse uploadPickingOutbound(
            @WebParam(partName = "uploadPickingOutboundRequest", name = "uploadPickingOutboundRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadPickingOutboundRequest uploadPickingOutboundRequest) throws AuthenticationFailedException;

    @WebResult(name = "getInventoryCheckResponse", targetNamespace = "", partName = "getInventoryCheckResponse")
    @WebMethod
    public GetInventoryCheckResponse getInventoryCheck(@WebParam(partName = "getInventoryCheckRequest", name = "getInventoryCheckRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetInventoryCheckRequest getInventoryCheckRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadLibraryMovementResponse", targetNamespace = "", partName = "uploadLibraryMovementResponse")
    @WebMethod
    public UploadLibraryMovementResponse uploadLibraryMovement(
            @WebParam(partName = "uploadLibraryMovementRequest", name = "uploadLibraryMovementRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadLibraryMovementRequest uploadLibraryMovementRequest) throws AuthenticationFailedException;

    @WebResult(name = "loginResponse", targetNamespace = "", partName = "loginResponse")
    @WebMethod
    public LoginResponse login(@WebParam(partName = "loginRequest", name = "loginRequest", targetNamespace = "http://webservice.jumbo.com/pda/") LoginRequest loginRequest) throws AuthenticationFailedException;

    @WebResult(name = "getReturnOrderResponse", targetNamespace = "", partName = "getReturnOrderResponse")
    @WebMethod
    public GetReturnOrderResponse getReturnOrder(@WebParam(partName = "getReturnOrderRequest", name = "getReturnOrderRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetReturnOrderRequest getReturnOrderRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadInboundReceiveResponse", targetNamespace = "", partName = "uploadInboundReceiveResponse")
    @WebMethod
    public UploadInboundReceiveResponse uploadInboundReceive(
            @WebParam(partName = "uploadInboundReceiveRequest", name = "uploadInboundReceiveRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadInboundReceiveRequest uploadInboundReceiveRequest) throws AuthenticationFailedException;

    @WebResult(name = "getLibraryMovementResponse", targetNamespace = "", partName = "getLibraryMovementResponse")
    @WebMethod
    public GetLibraryMovementResponse getLibraryMovement(@WebParam(partName = "getLibraryMovementRequest", name = "getLibraryMovementRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetLibraryMovementRequest getLibraryMovementRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "getPickingDataResponse", targetNamespace = "", partName = "getPickingDataResponse")
    @WebMethod
    public GetPickingDataResponse getPickingData(@WebParam(partName = "getPickingDataRequest", name = "getPickingDataRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetPickingDataRequest getPickingDataRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadInboundOnShelvesResponse", targetNamespace = "", partName = "uploadInboundOnShelvesResponse")
    @WebMethod
    public UploadInboundOnShelvesResponse uploadInboundOnShelves(
            @WebParam(partName = "uploadInboundOnShelvesRequest", name = "uploadInboundOnShelvesRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadInboundOnShelvesRequest uploadInboundOnShelvesRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "uploadHandOverListResponse", targetNamespace = "", partName = "uploadHandOverListResponse")
    @WebMethod
    public UploadHandOverListResponse uploadHandOverList(@WebParam(partName = "uploadHandOverListRequest", name = "uploadHandOverListRequest", targetNamespace = "http://webservice.jumbo.com/pda/") UploadHandOverListRequest uploadHandOverListRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "getTransNoResponse", targetNamespace = "", partName = "getTransNoResponse")
    @WebMethod
    public GetTransNoResponse getTransNo(@WebParam(partName = "getTransNoRequest", name = "getTransNoRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetTransNoRequest getTransNoRequest) throws AuthenticationFailedException;

    @WebResult(name = "getInventoryResponse", targetNamespace = "", partName = "getInventoryResponse")
    @WebMethod
    public GetInventoryResponse getInventory(@WebParam(partName = "getInventoryRequest", name = "getInventoryRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetInventoryRequest getInventoryRequest) throws AuthenticationFailedException;

    @WebResult(name = "getInboundDataResponse", targetNamespace = "", partName = "getInboundDataResponse")
    @WebMethod
    public GetInboundDataResponse getInboundData(@WebParam(partName = "getInboundDataRequest", name = "getInboundDataRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetInboundDataRequest getInboundDataRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "getInboundOnShelvesResponse", targetNamespace = "", partName = "getInboundOnShelvesResponse")
    @WebMethod
    public GetInboundOnShelvesResponse getInboundOnShelves(@WebParam(partName = "getInboundOnShelvesRequest", name = "getInboundOnShelvesRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetInboundOnShelvesRequest getInboundOnShelvesRequest)
            throws AuthenticationFailedException;

    @WebResult(name = "executeOrderResponse", targetNamespace = "", partName = "executeOrderResponse")
    @WebMethod
    public ExecuteOrderResponse executeOrder(@WebParam(partName = "executeOrderRequest", name = "executeOrderRequest", targetNamespace = "http://webservice.jumbo.com/pda/") ExecuteOrderRequest executeOrderRequest) throws AuthenticationFailedException;

    @WebResult(name = "getWarehousesResponse", targetNamespace = "", partName = "getWarehousesResponse")
    @WebMethod
    public GetWarehousesResponse getWarehouses(@WebParam(partName = "getWarehousesRequest", name = "getWarehousesRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetWarehousesRequest getWarehousesRequest)
            throws AuthenticationFailedException;
    
    @WebResult(name = "getSkuResponse", targetNamespace = "", partName = "getSkuResponse")
    @WebMethod
    public GetSkuResponse getSku(@WebParam(partName = "getSkuRequest", name = "getSkuRequest", targetNamespace = "http://webservice.jumbo.com/pda/") GetSkuRequest getSkuRequest)
            throws AuthenticationFailedException;
    
}
