package com.bt.workOrder.model;

/**
* @ClassName: FollowUpRecord
* @Description: TODO(FollowUpRecord)
* @author Yuriy.Jiang
* @date 2016年6月22日 上午10:19:25
*
*/
public class FollowUpRecord {
	
		private String id;			//主键	private java.util.Date create_time;			//创建时间	private String create_by;			//创建记录操作对象	private String create_by_display;			//	private Integer create_by_group;			//	private String create_by_group_display;			//	private String create_by_department;			//跟进人所在部门/店铺客服填店铺CODE，销售运营填SO	private String create_by_department_display;			//跟进人所在部门展示/店铺客服填店铺名，销售运营填销售运营部	private java.util.Date update_time;			//更新时间	private String update_by;			//更新记录操作对象	private String wo_store_id;			//工单ID	private String follow_up_record;			//	public String getId() {	    return this.id;	}	public void setId(String id) {	    this.id=id;	}	public java.util.Date getCreate_time() {	    return this.create_time;	}	public void setCreate_time(java.util.Date create_time) {	    this.create_time=create_time;	}	public String getCreate_by() {	    return this.create_by;	}	public void setCreate_by(String create_by) {	    this.create_by=create_by;	}	public String getCreate_by_display() {	    return this.create_by_display;	}	public void setCreate_by_display(String create_by_display) {	    this.create_by_display=create_by_display;	}	public Integer getCreate_by_group() {	    return this.create_by_group;	}	public void setCreate_by_group(Integer create_by_group) {	    this.create_by_group=create_by_group;	}	public String getCreate_by_group_display() {	    return this.create_by_group_display;	}	public void setCreate_by_group_display(String create_by_group_display) {	    this.create_by_group_display=create_by_group_display;	}	public String getCreate_by_department() {	    return this.create_by_department;	}	public void setCreate_by_department(String create_by_department) {	    this.create_by_department=create_by_department;	}	public String getCreate_by_department_display() {	    return this.create_by_department_display;	}	public void setCreate_by_department_display(String create_by_department_display) {	    this.create_by_department_display=create_by_department_display;	}	public java.util.Date getUpdate_time() {	    return this.update_time;	}	public void setUpdate_time(java.util.Date update_time) {	    this.update_time=update_time;	}	public String getUpdate_by() {	    return this.update_by;	}	public void setUpdate_by(String update_by) {	    this.update_by=update_by;	}	public String getWo_store_id() {	    return this.wo_store_id;	}	public void setWo_store_id(String wo_store_id) {	    this.wo_store_id=wo_store_id;	}	public String getFollow_up_record() {	    return this.follow_up_record;	}	public void setFollow_up_record(String follow_up_record) {	    this.follow_up_record=follow_up_record;	}
}
