package com.jumbo.webservice.sf.tw.order;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.jumbo.rmiservice.RmiServiceImpl;

/**
 * This class was generated by Apache CXF 3.0.3 2016-01-21T15:24:15.763+08:00 Generated source
 * version: 3.0.3
 * 
 */
public final class IOutsideToLscmService_OutsideToLscmServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.warehouse.integration.sf.com/", "OutsideToLscmServiceService");
    protected static final Logger logger = LoggerFactory.getLogger(RmiServiceImpl.class);

    private IOutsideToLscmService_OutsideToLscmServicePort_Client() {}

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OutsideToLscmServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                if (logger.isErrorEnabled()) {
                    logger.error("MalformedURLException", e);
                }
            }
        }

        OutsideToLscmServiceService ss = new OutsideToLscmServiceService(wsdlURL, SERVICE_NAME);
        IOutsideToLscmService port = ss.getOutsideToLscmServicePort();

        {
            System.out.println("Invoking yxToLscmService...");
            java.lang.String _yxToLscmService_arg0 = "";
            java.lang.String _yxToLscmService__return = port.yxToLscmService(_yxToLscmService_arg0);
            System.out.println("yxToLscmService.result=" + _yxToLscmService__return);


        }
        {
            System.out.println("Invoking jyToLscmService...");
            java.lang.String _jyToLscmService_arg0 = "";
            java.lang.String _jyToLscmService__return = port.jyToLscmService(_jyToLscmService_arg0);
            System.out.println("jyToLscmService.result=" + _jyToLscmService__return);


        }
        {
            System.out.println("Invoking outsideToLscmService...");
            java.lang.String _outsideToLscmService_arg0 = "";
            java.lang.String _outsideToLscmService__return = port.outsideToLscmService(_outsideToLscmService_arg0);
            System.out.println("outsideToLscmService.result=" + _outsideToLscmService__return);


        }

        System.exit(0);
    }

}
