//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:39:17 ���� CST 
//


package com.jumbo.webservice.sf.tw.outbound.command;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ErpOrderLineNum"/>
 *         &lt;element ref="{}SkuNo"/>
 *         &lt;element ref="{}ActualQty"/>
 *         &lt;element ref="{}QtyUm"/>
 *         &lt;element ref="{}Lot"/>
 *         &lt;element ref="{}Weight"/>
 *         &lt;element ref="{}WeightUm"/>
 *         &lt;element ref="{}InventoryStatus"/>
 *         &lt;element ref="{}LotAttr1"/>
 *         &lt;element ref="{}LotAttr2"/>
 *         &lt;element ref="{}LotAttr3"/>
 *         &lt;element ref="{}LotAttr4"/>
 *         &lt;element ref="{}LotAttr5"/>
 *         &lt;element ref="{}LotAttr6"/>
 *         &lt;element ref="{}UserDef1"/>
 *         &lt;element ref="{}UserDef2"/>
 *         &lt;element ref="{}UserDef3"/>
 *         &lt;element ref="{}UserDef4"/>
 *         &lt;element ref="{}UserDef5"/>
 *         &lt;element ref="{}UserDef6"/>
 *         &lt;element ref="{}UserDef7"/>
 *         &lt;element ref="{}UserDef8"/>
 *         &lt;element ref="{}SerialNumbers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "erpOrderLineNum",
    "skuNo",
    "actualQty",
    "qtyUm",
    "lot",
    "weight",
    "weightUm",
    "inventoryStatus",
    "lotAttr1",
    "lotAttr2",
    "lotAttr3",
    "lotAttr4",
    "lotAttr5",
    "lotAttr6",
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8",
    "serialNumbers"
})
@XmlRootElement(name = "Item")
public class OutboundRtnReqItem {

    @XmlElement(name = "ErpOrderLineNum", required = false)
    protected String erpOrderLineNum;
    @XmlElement(name = "SkuNo", required = true)
    protected String skuNo;
    @XmlElement(name = "ActualQty", required = true)
    protected BigDecimal actualQty;
    @XmlElement(name = "QtyUm", required = false)
    protected String qtyUm;
    @XmlElement(name = "Lot", required = false)
    protected String lot;
    @XmlElement(name = "Weight", required = false)
    protected BigDecimal weight;
    @XmlElement(name = "WeightUm", required = false)
    protected String weightUm;
    @XmlElement(name = "InventoryStatus", required = false)
    protected String inventoryStatus;
    @XmlElement(name = "LotAttr1", required = false)
    protected String lotAttr1;
    @XmlElement(name = "LotAttr2", required = false)
    protected String lotAttr2;
    @XmlElement(name = "LotAttr3", required = false)
    protected String lotAttr3;
    @XmlElement(name = "LotAttr4", required = false)
    protected String lotAttr4;
    @XmlElement(name = "LotAttr5", required = false)
    protected String lotAttr5;
    @XmlElement(name = "LotAttr6", required = false)
    protected String lotAttr6;
    @XmlElement(name = "UserDef1", required = false)
    protected String userDef1;
    @XmlElement(name = "UserDef2", required = false)
    protected String userDef2;
    @XmlElement(name = "UserDef3", required = false)
    protected String userDef3;
    @XmlElement(name = "UserDef4", required = false)
    protected String userDef4;
    @XmlElement(name = "UserDef5", required = false)
    protected String userDef5;
    @XmlElement(name = "UserDef6", required = false)
    protected String userDef6;
    @XmlElement(name = "UserDef7", required = false)
    protected String userDef7;
    @XmlElement(name = "UserDef8", required = false)
    protected String userDef8;
    @XmlElement(name = "SerialNumbers", required = false)
    protected OutboundRtnReqSerialNumbers serialNumbers;

    /**
     * Gets the value of the erpOrderLineNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErpOrderLineNum() {
        return erpOrderLineNum;
    }

    /**
     * Sets the value of the erpOrderLineNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErpOrderLineNum(String value) {
        this.erpOrderLineNum = value;
    }

    /**
     * Gets the value of the skuNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * Sets the value of the skuNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuNo(String value) {
        this.skuNo = value;
    }

    /**
     * Gets the value of the actualQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualQty() {
        return actualQty;
    }

    /**
     * Sets the value of the actualQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualQty(BigDecimal value) {
        this.actualQty = value;
    }

    /**
     * Gets the value of the qtyUm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyUm() {
        return qtyUm;
    }

    /**
     * Sets the value of the qtyUm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyUm(String value) {
        this.qtyUm = value;
    }

    /**
     * Gets the value of the lot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLot() {
        return lot;
    }

    /**
     * Sets the value of the lot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLot(String value) {
        this.lot = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightUm() {
        return weightUm;
    }

    /**
     * Sets the value of the weightUm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightUm(String value) {
        this.weightUm = value;
    }

    /**
     * Gets the value of the inventoryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryStatus() {
        return inventoryStatus;
    }

    /**
     * Sets the value of the inventoryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryStatus(String value) {
        this.inventoryStatus = value;
    }

    /**
     * Gets the value of the lotAttr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr1() {
        return lotAttr1;
    }

    /**
     * Sets the value of the lotAttr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr1(String value) {
        this.lotAttr1 = value;
    }

    /**
     * Gets the value of the lotAttr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr2() {
        return lotAttr2;
    }

    /**
     * Sets the value of the lotAttr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr2(String value) {
        this.lotAttr2 = value;
    }

    /**
     * Gets the value of the lotAttr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr3() {
        return lotAttr3;
    }

    /**
     * Sets the value of the lotAttr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr3(String value) {
        this.lotAttr3 = value;
    }

    /**
     * Gets the value of the lotAttr4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr4() {
        return lotAttr4;
    }

    /**
     * Sets the value of the lotAttr4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr4(String value) {
        this.lotAttr4 = value;
    }

    /**
     * Gets the value of the lotAttr5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr5() {
        return lotAttr5;
    }

    /**
     * Sets the value of the lotAttr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr5(String value) {
        this.lotAttr5 = value;
    }

    /**
     * Gets the value of the lotAttr6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttr6() {
        return lotAttr6;
    }

    /**
     * Sets the value of the lotAttr6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttr6(String value) {
        this.lotAttr6 = value;
    }

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

    /**
     * Gets the value of the serialNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumbers }
     *     
     */
    public OutboundRtnReqSerialNumbers getSerialNumbers() {
        return serialNumbers;
    }

    /**
     * Sets the value of the serialNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumbers }
     *     
     */
    public void setSerialNumbers(OutboundRtnReqSerialNumbers value) {
        this.serialNumbers = value;
    }
}
