//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:39:17 ���� CST 
//


package com.jumbo.webservice.sf.tw.outbound.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}WarehouseCode"/>
 *         &lt;element ref="{}ErpOrder"/>
 *         &lt;element ref="{}ShipmentId"/>
 *         &lt;element ref="{}WayBillNo"/>
 *         &lt;element ref="{}ReturnTracking"/>
 *         &lt;element ref="{}ActualShipDateTime"/>
 *         &lt;element ref="{}Carrier"/>
 *         &lt;element ref="{}CarrierProduct"/>
 *         &lt;element ref="{}ErpOrderType"/>
 *         &lt;element ref="{}InvoiceNo"/>
 *         &lt;element ref="{}IsSplit"/>
 *         &lt;element ref="{}DataStatus"/>
 *         &lt;element ref="{}UserDef1"/>
 *         &lt;element ref="{}UserDef2"/>
 *         &lt;element ref="{}UserDef3"/>
 *         &lt;element ref="{}UserDef4"/>
 *         &lt;element ref="{}UserDef5"/>
 *         &lt;element ref="{}UserDef6"/>
 *         &lt;element ref="{}UserDef7"/>
 *         &lt;element ref="{}UserDef8"/>
 *         &lt;element ref="{}Items"/>
 *         &lt;element ref="{}Containers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "warehouseCode",
    "erpOrder",
    "shipmentId",
    "wayBillNo",
    "returnTracking",
    "actualShipDateTime",
    "carrier",
    "carrierProduct",
    "erpOrderType",
    "invoiceNo",
    "isSplit",
    "dataStatus",
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8",
    "items",
    "containers"
})
@XmlRootElement(name = "SaleOrder")
public class OutboundRtnReqSaleOrder {

    @XmlElement(name = "WarehouseCode", required = true)
    protected String warehouseCode;
    @XmlElement(name = "ErpOrder", required = true)
    protected String erpOrder;
    @XmlElement(name = "ShipmentId", required = true)
    protected String shipmentId;
    @XmlElement(name = "WayBillNo", required = true)
    protected String wayBillNo;
    @XmlElement(name = "ReturnTracking", required = true)
    protected String returnTracking;
    @XmlElement(name = "ActualShipDateTime", required = true)
    protected String actualShipDateTime;
    @XmlElement(name = "Carrier", required = true)
    protected String carrier;
    @XmlElement(name = "CarrierProduct", required = true)
    protected String carrierProduct;
    @XmlElement(name = "ErpOrderType", required = true)
    protected String erpOrderType;
    @XmlElement(name = "InvoiceNo", required = true)
    protected String invoiceNo;
    @XmlElement(name = "IsSplit", required = true)
    protected String isSplit;
    @XmlElement(name = "DataStatus", required = true)
    protected String dataStatus;
    @XmlElement(name = "UserDef1", required = true)
    protected String userDef1;
    @XmlElement(name = "UserDef2", required = true)
    protected String userDef2;
    @XmlElement(name = "UserDef3", required = true)
    protected String userDef3;
    @XmlElement(name = "UserDef4", required = true)
    protected String userDef4;
    @XmlElement(name = "UserDef5", required = true)
    protected String userDef5;
    @XmlElement(name = "UserDef6", required = true)
    protected String userDef6;
    @XmlElement(name = "UserDef7", required = true)
    protected String userDef7;
    @XmlElement(name = "UserDef8", required = true)
    protected String userDef8;
    @XmlElement(name = "Items", required = true)
    protected OutboundRtnReqItems items;
    @XmlElement(name = "Containers", required = true)
    protected OutboundRtnReqContainers containers;

    /**
     * Gets the value of the warehouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * Sets the value of the warehouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseCode(String value) {
        this.warehouseCode = value;
    }

    /**
     * Gets the value of the erpOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErpOrder() {
        return erpOrder;
    }

    /**
     * Sets the value of the erpOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErpOrder(String value) {
        this.erpOrder = value;
    }

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentId(String value) {
        this.shipmentId = value;
    }

    /**
     * Gets the value of the wayBillNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWayBillNo() {
        return wayBillNo;
    }

    /**
     * Sets the value of the wayBillNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWayBillNo(String value) {
        this.wayBillNo = value;
    }

    /**
     * Gets the value of the returnTracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnTracking() {
        return returnTracking;
    }

    /**
     * Sets the value of the returnTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnTracking(String value) {
        this.returnTracking = value;
    }

    /**
     * Gets the value of the actualShipDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualShipDateTime() {
        return actualShipDateTime;
    }

    /**
     * Sets the value of the actualShipDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualShipDateTime(String value) {
        this.actualShipDateTime = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the carrierProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierProduct() {
        return carrierProduct;
    }

    /**
     * Sets the value of the carrierProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierProduct(String value) {
        this.carrierProduct = value;
    }

    /**
     * Gets the value of the erpOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErpOrderType() {
        return erpOrderType;
    }

    /**
     * Sets the value of the erpOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErpOrderType(String value) {
        this.erpOrderType = value;
    }

    /**
     * Gets the value of the invoiceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * Sets the value of the invoiceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNo(String value) {
        this.invoiceNo = value;
    }

    /**
     * Gets the value of the isSplit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSplit() {
        return isSplit;
    }

    /**
     * Sets the value of the isSplit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSplit(String value) {
        this.isSplit = value;
    }

    /**
     * Gets the value of the dataStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * Sets the value of the dataStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataStatus(String value) {
        this.dataStatus = value;
    }

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundRtnReqItems }
     *     
     */
    public OutboundRtnReqItems getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundRtnReqItems }
     *     
     */
    public void setItems(OutboundRtnReqItems value) {
        this.items = value;
    }

    /**
     * Gets the value of the containers property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundRtnReqContainers }
     *     
     */
    public OutboundRtnReqContainers getContainers() {
        return containers;
    }

    /**
     * Sets the value of the containers property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundRtnReqContainers }
     *     
     */
    public void setContainers(OutboundRtnReqContainers value) {
        this.containers = value;
    }

}
