//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:39:17 ���� CST 
//


package com.jumbo.webservice.sf.tw.outbound.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SaleOrderOutboundDetailRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saleOrderOutboundDetailRequest"
})
@XmlRootElement(name = "Body")
public class OutboundRtnReqBody {

    @XmlElement(name = "SaleOrderOutboundDetailRequest", required = true)
    protected OutboundRtnSaleOrderOutboundDetailRequest saleOrderOutboundDetailRequest;

    /**
     * Gets the value of the saleOrderOutboundDetailRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundRtnSaleOrderOutboundDetailRequest }
     *     
     */
    public OutboundRtnSaleOrderOutboundDetailRequest getSaleOrderOutboundDetailRequest() {
        return saleOrderOutboundDetailRequest;
    }

    /**
     * Sets the value of the saleOrderOutboundDetailRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundRtnSaleOrderOutboundDetailRequest }
     *     
     */
    public void setSaleOrderOutboundDetailRequest(OutboundRtnSaleOrderOutboundDetailRequest value) {
        this.saleOrderOutboundDetailRequest = value;
    }

}
