//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.13 at 10:18:18 ���� CST
//


package com.jumbo.wms.model.command.vmi.esprit.xml.order;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sku" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="7000000003028"/>
 *             &lt;enumeration value="7000000003035"/>
 *             &lt;enumeration value="7000000003042"/>
 *             &lt;enumeration value="7000000003059"/>
 *             &lt;enumeration value="7000000003066"/>
 *             &lt;enumeration value="7000000003073"/>
 *             &lt;enumeration value="7000000003080"/>
 *             &lt;enumeration value="7000000003097"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="orderQty" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="100"/>
 *             &lt;enumeration value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fobInCurrency" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="33.00"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="globalTransferPrice" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="0.00"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "item")
public class EspritItemXml implements Serializable {


    private static final long serialVersionUID = 1448291423725222017L;
    @XmlAttribute(required = true)
    public String sku;
    @XmlAttribute(required = true)
    public String orderQty;
    @XmlAttribute(required = true)
    public String fobInCurrency;
    @XmlAttribute(required = true)
    public String globalTransferPrice;

    /**
     * Gets the value of the sku property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSku(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the orderQty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrderQty() {
        return orderQty;
    }

    /**
     * Sets the value of the orderQty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOrderQty(String value) {
        this.orderQty = value;
    }

    /**
     * Gets the value of the fobInCurrency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFobInCurrency() {
        return fobInCurrency;
    }

    /**
     * Sets the value of the fobInCurrency property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFobInCurrency(String value) {
        this.fobInCurrency = value;
    }

    /**
     * Gets the value of the globalTransferPrice property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalTransferPrice() {
        return globalTransferPrice;
    }

    /**
     * Sets the value of the globalTransferPrice property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setGlobalTransferPrice(String value) {
        this.globalTransferPrice = value;
    }

}
