//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.13 at 10:18:18 ���� CST
//


package com.jumbo.wms.model.command.vmi.esprit.xml.order;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}buyingSeasonYear"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}buyingSeasonCode"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}style"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}po"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}factory"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}supplier"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}countryOfOrigin"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}currency"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}expectedDeliveryDate"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}shippingMethod"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}exFactoryDate"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}portOfLoading"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}statusInEDIFile"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}fromNodeGLN"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}toNodeGLN"/>
 *         &lt;element ref="{http://www.esprit.com.cn/XMLSchema/eShopInterface/espOrder.xsd}orderDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"buyingSeasonYear", "buyingSeasonCode", "style", "po", "poReference", "factory", "supplier", "countryOfOrigin", "currency", "expectedDeliveryDate", "shippingMethod", "exFactoryDate", "portOfLoading", "statusInEDIFile",
        "fromNodeGLN", "toNodeGLN", "orderDetails"})
@XmlRootElement(name = "order")
public class EspritOrderXml implements Serializable {


    private static final long serialVersionUID = 2598120899395574633L;
    @XmlElement(required = true)
    public String buyingSeasonYear;
    @XmlElement(required = true)
    public String buyingSeasonCode;
    @XmlElement(required = true)
    public String style;
    @XmlElement(required = true)
    public String po;
    @XmlElement(required = true)
    public String poReference;
    @XmlElement(required = true)
    public String factory;
    @XmlElement(required = true)
    public String supplier;
    @XmlElement(required = true)
    public String countryOfOrigin;
    @XmlElement(required = true)
    public String currency;
    @XmlElement(required = true)
    public String expectedDeliveryDate;
    @XmlElement(required = true)
    public String shippingMethod;
    @XmlElement(required = true)
    public String exFactoryDate;
    @XmlElement(required = true)
    public String portOfLoading;
    @XmlElement(required = true)
    public String statusInEDIFile;
    @XmlElement(required = true)
    public String fromNodeGLN;
    @XmlElement(required = true)
    public String toNodeGLN;
    @XmlElement(required = true)
    public EspritOrderDetailsXml orderDetails;

    /**
     * Gets the value of the buyingSeasonYear property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBuyingSeasonYear() {
        return buyingSeasonYear;
    }

    /**
     * Sets the value of the buyingSeasonYear property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBuyingSeasonYear(String value) {
        this.buyingSeasonYear = value;
    }

    /**
     * Gets the value of the buyingSeasonCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBuyingSeasonCode() {
        return buyingSeasonCode;
    }

    /**
     * Sets the value of the buyingSeasonCode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBuyingSeasonCode(String value) {
        this.buyingSeasonCode = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the po property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPo() {
        return po;
    }

    /**
     * Sets the value of the po property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPo(String value) {
        this.po = value;
    }

    /**
     * Gets the value of the factory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFactory() {
        return factory;
    }

    /**
     * Sets the value of the factory property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFactory(String value) {
        this.factory = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSupplier(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the expectedDeliveryDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    /**
     * Sets the value of the expectedDeliveryDate property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExpectedDeliveryDate(String value) {
        this.expectedDeliveryDate = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setShippingMethod(String value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the exFactoryDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExFactoryDate() {
        return exFactoryDate;
    }

    /**
     * Sets the value of the exFactoryDate property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExFactoryDate(String value) {
        this.exFactoryDate = value;
    }

    /**
     * Gets the value of the portOfLoading property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPortOfLoading() {
        return portOfLoading;
    }

    /**
     * Sets the value of the portOfLoading property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPortOfLoading(String value) {
        this.portOfLoading = value;
    }

    /**
     * Gets the value of the statusInEDIFile property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusInEDIFile() {
        return statusInEDIFile;
    }

    /**
     * Sets the value of the statusInEDIFile property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatusInEDIFile(String value) {
        this.statusInEDIFile = value;
    }

    /**
     * Gets the value of the fromNodeGLN property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFromNodeGLN() {
        return fromNodeGLN;
    }

    /**
     * Sets the value of the fromNodeGLN property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFromNodeGLN(String value) {
        this.fromNodeGLN = value;
    }

    /**
     * Gets the value of the toNodeGLN property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getToNodeGLN() {
        return toNodeGLN;
    }

    /**
     * Sets the value of the toNodeGLN property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setToNodeGLN(String value) {
        this.toNodeGLN = value;
    }

    /**
     * Gets the value of the orderDetails property.
     * 
     * @return possible object is {@link EspritOrderDetailsXml }
     * 
     */
    public EspritOrderDetailsXml getOrderDetails() {
        return orderDetails;
    }

    /**
     * Sets the value of the orderDetails property.
     * 
     * @param value allowed object is {@link EspritOrderDetailsXml }
     * 
     */
    public void setOrderDetails(EspritOrderDetailsXml value) {
        this.orderDetails = value;
    }

    public String getPoReference() {
        return poReference;
    }

    public void setPoReference(String poReference) {
        this.poReference = poReference;
    }

}
