//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.13 at 03:48:57 PM CST
//

package com.jumbo.webservice.ids.command;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batchId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="district" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="totalAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="logisticFee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderLine" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"batchId", "totalQty", "order"})
@XmlRootElement(name = "orderList")
public class OrderList implements Serializable {


    /**
     * 
     */
    private static final long serialVersionUID = -4282901336171344982L;
    @XmlElement(required = true)
    protected String batchId = "";
    @XmlElement(required = true)
    protected String totalQty = "";
    @XmlElement(required = true)
    protected List<OrderList.Order> order;

    /**
     * Gets the value of the batchId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBatchId(String value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the totalQty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalQty() {
        return totalQty;
    }

    /**
     * Sets the value of the totalQty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTotalQty(String value) {
        this.totalQty = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
	 * getOrder().add(newItem);
	 * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link OrderList.Order }
     * 
     * 
     */
    public List<OrderList.Order> getOrder() {
        if (order == null) {
            order = new ArrayList<OrderList.Order>();
        }
        return this.order;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="district" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="totalAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="logisticFee" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="orderLine" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"code", "plfCode", "storeCode", "type", "createTime", "country", "province", "city", "district", "address", "zipcode", "telephone", "mobile", "receiver", "logistic", "totalAmt", "logisticFee", "remark", "sender",
            "senderTel", "senderAddress", "sfCode", "transNo", "cityCode", "isCod", "totalActual", "orderLine"})
    public static class Order implements Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = -3707246882236713939L;
		public final static String JD = "JDEX";
        @XmlElement(required = true)
        protected String code = "";
        @XmlElement(required = true)
        protected String plfCode = "";
        @XmlElement(required = true)
        protected String storeCode = "";
        @XmlElement(required = true)
        protected String type = "";
        @XmlElement(required = true)
        protected String createTime = "";
        @XmlElement(required = true)
        protected String country = "";
        @XmlElement(required = true)
        protected String province = "";
        @XmlElement(required = true)
        protected String city = "";
        @XmlElement(required = true)
        protected String district = "";
        @XmlElement(required = true)
        protected String address = "";
        @XmlElement(required = true)
        protected String zipcode = "";
        @XmlElement(required = true)
        protected String telephone = "";
        @XmlElement(required = true)
        protected String mobile = "";
        @XmlElement(required = true)
        protected String receiver = "";
        @XmlElement(required = true)
        protected String logistic = "";
        @XmlElement(required = true)
        protected String totalAmt = "";
        @XmlElement(required = true)
        protected String logisticFee = "";
        @XmlElement(required = true)
        protected String remark = "";
        @XmlElement(required = true)
        protected String sender = "";
        @XmlElement(required = true)
        protected String senderTel = "";
        @XmlElement(required = true)
        protected String senderAddress = "";
        @XmlElement(required = true)
        protected String sfCode = "";
        @XmlElement(required = true)
        protected String transNo = "";
        @XmlElement(required = true)
        protected String cityCode = "";
        @XmlElement(required = true)
        protected String isCod = "";
        @XmlElement(required = true)
        protected String totalActual = "";
        @XmlElement(required = true)
        protected List<OrderList.Order.OrderLine> orderLine;

        /**
         * Gets the value of the code property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the plfCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPlfCode() {
            return plfCode;
        }

        /**
         * Sets the value of the plfCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setPlfCode(String value) {
            this.plfCode = value;
        }

        /**
         * Gets the value of the storeCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getStoreCode() {
            return storeCode;
        }

        /**
         * Sets the value of the storeCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setStoreCode(String value) {
            this.storeCode = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the createTime property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCreateTime() {
            return createTime;
        }

        /**
         * Sets the value of the createTime property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCreateTime(String value) {
            this.createTime = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the province property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getProvince() {
            return province;
        }

        /**
         * Sets the value of the province property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setProvince(String value) {
            this.province = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the district property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDistrict() {
            return district;
        }

        /**
         * Sets the value of the district property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setDistrict(String value) {
            this.district = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the zipcode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getZipcode() {
            return zipcode;
        }

        /**
         * Sets the value of the zipcode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setZipcode(String value) {
            this.zipcode = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the mobile property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getMobile() {
            return mobile;
        }

        /**
         * Sets the value of the mobile property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setMobile(String value) {
            this.mobile = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getReceiver() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setReceiver(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the logistic property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLogistic() {
            return logistic;
        }

        /**
         * Sets the value of the logistic property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLogistic(String value) {
            this.logistic = value;
        }

        /**
         * Gets the value of the totalAmt property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTotalAmt() {
            return totalAmt;
        }

        /**
         * Sets the value of the totalAmt property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTotalAmt(String value) {
            this.totalAmt = value;
        }

        /**
         * Gets the value of the logisticFee property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLogisticFee() {
            return logisticFee;
        }

        /**
         * Sets the value of the logisticFee property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLogisticFee(String value) {
            this.logisticFee = value;
        }

        /**
         * Gets the value of the remark property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getRemark() {
            return remark;
        }

        /**
         * Sets the value of the remark property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setRemark(String value) {
            this.remark = value;
        }

        public String getSender() {
            return sender;
        }

        public void setSender(String sender) {
            this.sender = sender;
        }

        public String getSenderTel() {
            return senderTel;
        }

        public void setSenderTel(String senderTel) {
            this.senderTel = senderTel;
        }

        public String getSenderAddress() {
            return senderAddress;
        }

        public void setSenderAddress(String senderAddress) {
            this.senderAddress = senderAddress;
        }

        public String getSfCode() {
            return sfCode;
        }

        public void setSfCode(String sfCode) {
            this.sfCode = sfCode;
        }

        public String getTransNo() {
            return transNo;
        }

        public void setTransNo(String transNo) {
            this.transNo = transNo;
        }

        public String getCityCode() {
            return cityCode;
        }

        public void setCityCode(String cityCode) {
            this.cityCode = cityCode;
        }

        public String getIsCod() {
            return isCod;
        }

        public void setIsCod(String isCod) {
            this.isCod = isCod;
        }

        public String getTotalActual() {
            return totalActual;
        }

        public void setTotalActual(String totalActual) {
            this.totalActual = totalActual;
        }

        public void setOrderLine(List<OrderList.Order.OrderLine> orderLine) {
            this.orderLine = orderLine;
        }

        /**
         * Gets the value of the orderLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the orderLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
		 * getOrderLine().add(newItem);
		 * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderList.Order.OrderLine }
         * 
         * 
         */
        public List<OrderList.Order.OrderLine> getOrderLine() {
            if (orderLine == null) {
                orderLine = new ArrayList<OrderList.Order.OrderLine>();
            }
            return this.orderLine;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"code", "sku", "bzskuCode", "barcode", "quantity"})
        public static class OrderLine implements Serializable {
            /**
			 * 
			 */
			private static final long serialVersionUID = 8467563689938576181L;
			@XmlElement(required = true)
            protected String code = "";
            @XmlElement(required = true)
            protected String sku = "";
            @XmlElement(required = true)
            protected String bzskuCode = "";
            @XmlElement(required = true)
            protected String barcode = "";
            @XmlElement(required = true)
            protected String quantity = "";

            public String getCode() {
                return code;
            }

            public void setCode(String code) {
                this.code = code;
            }

            /**
             * Gets the value of the sku property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getSku() {
                return sku;
            }

            /**
             * Sets the value of the sku property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setSku(String value) {
                this.sku = value;
            }

            /**
             * Gets the value of the bzskuCode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBzskuCode() {
                return bzskuCode;
            }

            /**
             * Sets the value of the bzskuCode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBzskuCode(String value) {
                this.bzskuCode = value;
            }

            /**
             * Gets the value of the barcode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBarcode() {
                return barcode;
            }

            /**
             * Sets the value of the barcode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBarcode(String value) {
                this.barcode = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

        }

    }

}
