//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.20 at 05:04:21 PM CST
//

package com.jumbo.webservice.ids.command;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="outboundTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trackingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"totalQty", "order"})
@XmlRootElement(name = "orderOutbound")
public class OrderOutbound implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1438071003266149874L;
    @XmlElement(required = true)
    protected String totalQty = "";
    @XmlElement(required = true)
    protected List<OrderOutbound.Order> order;

    /**
     * Gets the value of the totalQty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalQty() {
        return totalQty;
    }

    /**
     * Sets the value of the totalQty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTotalQty(String value) {
        this.totalQty = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
	 * getOrder().add(newItem);
	 * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link OrderOutbound.Order }
     * 
     * 
     */
    public List<OrderOutbound.Order> getOrder() {
        if (order == null) {
            order = new ArrayList<OrderOutbound.Order>();
        }
        return this.order;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="outboundTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="trackingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"code", "outboundTime", "type", "logistic", "trackingCode", "weight"})
    public static class Order implements Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = -4152028117356173124L;
		@XmlElement(required = true)
        protected String code = "";
        @XmlElement(required = true)
        protected String outboundTime = "";
        @XmlElement(required = true)
        protected String type = "";
        @XmlElement(required = true)
        protected String logistic = "";
        @XmlElement(required = true)
        protected String trackingCode = "";
        @XmlElement(required = true)
        protected String weight = "";

        /**
         * Gets the value of the code property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the outboundTime property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getOutboundTime() {
            return outboundTime;
        }

        /**
         * Sets the value of the outboundTime property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setOutboundTime(String value) {
            this.outboundTime = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the logistic property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLogistic() {
            return logistic;
        }

        /**
         * Sets the value of the logistic property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLogistic(String value) {
            this.logistic = value;
        }

        /**
         * Gets the value of the trackingCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTrackingCode() {
            return trackingCode;
        }

        /**
         * Sets the value of the trackingCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTrackingCode(String value) {
            this.trackingCode = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setWeight(String value) {
            this.weight = value;
        }

    }

}
