/*
 * 
 */

package com.jumbo.webservice.sf.order;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * This class was generated by Apache CXF 2.2.9 Fri May 30 11:27:55 CST 2014 Generated source
 * version: 2.2.9
 * 
 */


@WebServiceClient(name = "OutsideToLscmServiceService", wsdlLocation = "file:OutsideToLscmServiceImpl.wsdl", targetNamespace = "http://service.warehouse.integration.sf.com/")
public class OutsideToLscmServiceService extends Service implements Serializable {

    /**
     * 
     */
    protected static final Logger log = LoggerFactory.getLogger(OutsideToLscmServiceService.class);
    private static final long serialVersionUID = 637019120031025877L;
    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.warehouse.integration.sf.com/", "OutsideToLscmServiceService");
    public final static QName OutsideToLscmServicePort = new QName("http://service.warehouse.integration.sf.com/", "OutsideToLscmServicePort");
    static {
        URL url = null;
        try {
            url = new URL(OutsideToLscmServiceService.class.getResource("/") + "wsdl/OutsideToLscmServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            // System.err.println("Can not initialize the default wsdl from file:OutsideToLscmServiceImpl.wsdl");
            // e.printStackTrace();
            if (log.isErrorEnabled()) {
                log.error("MalformedURLException！", e);
            }
        }
        WSDL_LOCATION = url;
    }

    public OutsideToLscmServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OutsideToLscmServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutsideToLscmServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * 
     * @return returns IOutsideToLscmService
     */
    @WebEndpoint(name = "OutsideToLscmServicePort")
    public IOutsideToLscmService getOutsideToLscmServicePort() {
        return super.getPort(OutsideToLscmServicePort, IOutsideToLscmService.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *        Supported features not in the <code>features</code> parameter will have their default
     *        values.
     * @return returns IOutsideToLscmService
     */
    @WebEndpoint(name = "OutsideToLscmServicePort")
    public IOutsideToLscmService getOutsideToLscmServicePort(WebServiceFeature... features) {
        return super.getPort(OutsideToLscmServicePort, IOutsideToLscmService.class, features);
    }

}
