package com.jumbo.webservice.biaogan.clientNew2;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import javax.xml.namespace.QName;

import com.jumbo.mq.MarshallerUtil;
import com.jumbo.webservice.biaogan.clientNew2.base.BMLQuery;
import com.jumbo.webservice.biaogan.clientNew2.base.BMLQueryPortType;
import com.jumbo.webservice.biaogan.command.InOutBoundResponse;
import com.jumbo.webservice.biaogan.command.InvoicesResponseCommand;

/**
 * This class was generated by Apache CXF 2.5.2 2012-03-19T12:59:29.306+08:00 Generated source
 * version: 2.5.2
 * 
 */
public final class PushExpressInfoPortTypeClientNew2 {

    private static final QName SERVICE_NAME = new QName("http://BML", "BMLQuery");

    private static final String USERNAME = "BZ_ALL";
    private static final String PASSWORD = "BML33570";

    private PushExpressInfoPortTypeClientNew2() {}

    /**
     * 发送出库通知
     * 
     * @param xml
     * @return
     */
    public static InOutBoundResponse soToWms(String xml) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.soToWms(USERNAME, PASSWORD, xml);
        return (InOutBoundResponse) MarshallerUtil.buildJaxb(InOutBoundResponse.class, _return);
    }

    /**
     * 发送入库通知
     * 
     * @param xml
     * @return
     */
    public static InOutBoundResponse ansToWms(String xml) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.ansToWms(USERNAME, PASSWORD, xml);
        return (InOutBoundResponse) MarshallerUtil.buildJaxb(InOutBoundResponse.class, _return);
    }

    /**
     * 取消订单
     * 
     * @param orderCode
     * @return
     */
    public static InOutBoundResponse cancelOrderRX(String orderCode) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.cancelOrderRX(USERNAME, PASSWORD, orderCode);
        return (InOutBoundResponse) MarshallerUtil.buildJaxb(InOutBoundResponse.class, _return);
    }

    /**
     * 取消入库单
     * 
     * @param orderCode
     * @return
     */
    public static InOutBoundResponse cancelAsnRX(String inBoundCode) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.cancelAsnRX(USERNAME, PASSWORD, inBoundCode);
        return (InOutBoundResponse) MarshallerUtil.buildJaxb(InOutBoundResponse.class, _return);
    }

    /**
     * 同步sku
     * 
     * @param xml
     */
    public static InOutBoundResponse singleSkuToWms(String xml) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.singleSkuToWms(USERNAME, PASSWORD, xml);
        return (InOutBoundResponse) MarshallerUtil.buildJaxb(InOutBoundResponse.class, _return);
    }

    /**
     * 发送发票
     * 
     * @param xml
     */
    public static InvoicesResponseCommand sendInvoices(String xml) {
        BMLQuery ss = new BMLQuery(BMLQuery.WSDL_LOCATION, SERVICE_NAME);
        BMLQueryPortType port = ss.getBMLQueryHttpPort();
        String _return = port.invoiceFromBZ(USERNAME, PASSWORD, xml);
        return (InvoicesResponseCommand) MarshallerUtil.buildJaxb(InvoicesResponseCommand.class, _return);
    }

    public static void main(String[] args) {
        String xml = "";
        InOutBoundResponse r = singleSkuToWms(xml);
        System.out.println(r.getSuccess());
        System.out.println(r.getCode());
        System.out.println(r.getDesc());
    }
}
