//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 10:54:18 ���� CST 
//


package com.jumbo.webservice.sf.tw.inbound.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PurchaseOrderInboundRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "purchaseOrderInboundRequest"
})
@XmlRootElement(name = "Body")
public class InboundRtnReqBody {

    @XmlElement(name = "PurchaseOrderInboundRequest", required = true)
    protected InboundRtnPurchaseOrderInboundRequest purchaseOrderInboundRequest;

    /**
     * Gets the value of the purchaseOrderInboundRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InboundRtnPurchaseOrderInboundRequest }
     *     
     */
    public InboundRtnPurchaseOrderInboundRequest getPurchaseOrderInboundRequest() {
        return purchaseOrderInboundRequest;
    }

    /**
     * Sets the value of the purchaseOrderInboundRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundRtnPurchaseOrderInboundRequest }
     *     
     */
    public void setPurchaseOrderInboundRequest(InboundRtnPurchaseOrderInboundRequest value) {
        this.purchaseOrderInboundRequest = value;
    }

}
