//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 07:05:00 ���� CST 
//


package com.jumbo.webservice.sf.tw.inbound.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PurchaseOrderInboundResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "purchaseOrderInboundResponse"
})
@XmlRootElement(name = "Body")
public class InboundRtnRespBody {

    @XmlElement(name = "PurchaseOrderInboundResponse", required = true)
    protected InboundRtnPurchaseOrderInboundResponse purchaseOrderInboundResponse;

    /**
     * Gets the value of the purchaseOrderInboundResponse property.
     * 
     * @return
     *     possible object is
     *     {@link InboundRtnPurchaseOrderInboundResponse }
     *     
     */
    public InboundRtnPurchaseOrderInboundResponse getPurchaseOrderInboundResponse() {
        return purchaseOrderInboundResponse;
    }

    /**
     * Sets the value of the purchaseOrderInboundResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundRtnPurchaseOrderInboundResponse }
     *     
     */
    public void setPurchaseOrderInboundResponse(InboundRtnPurchaseOrderInboundResponse value) {
        this.purchaseOrderInboundResponse = value;
    }

}
