//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 05:03:07 ���� CST 
//


package com.jumbo.webservice.sf.tw.inbound.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}WarehouseCode"/>
 *         &lt;element ref="{}ErpOrder"/>
 *         &lt;element ref="{}ErpOrderType"/>
 *         &lt;element ref="{}SFOrderType"/>
 *         &lt;element ref="{}OrderDate"/>
 *         &lt;element ref="{}Buyer"/>
 *         &lt;element ref="{}BuyerPhone"/>
 *         &lt;element ref="{}ScheduledReceiptDate"/>
 *         &lt;element ref="{}VendorCode"/>
 *         &lt;element ref="{}TransferWarehouseCode"/>
 *         &lt;element ref="{}OriginalOrderNo"/>
 *         &lt;element ref="{}Note"/>
 *         &lt;element ref="{}ReceiptMode"/>
 *         &lt;element ref="{}LicensePlateNumber"/>
 *         &lt;element ref="{}Driver"/>
 *         &lt;element ref="{}TradePlatform"/>
 *         &lt;element ref="{}TradeOrder"/>
 *         &lt;element ref="{}DriverCalls"/>
 *         &lt;element ref="{}UserDef1"/>
 *         &lt;element ref="{}UserDef2"/>
 *         &lt;element ref="{}UserDef3"/>
 *         &lt;element ref="{}UserDef4"/>
 *         &lt;element ref="{}UserDef5"/>
 *         &lt;element ref="{}UserDef6"/>
 *         &lt;element ref="{}UserDef7"/>
 *         &lt;element ref="{}UserDef8"/>
 *         &lt;element ref="{}Items"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "warehouseCode",
    "erpOrder",
    "erpOrderType",
    "sfOrderType",
    "orderDate",
    "buyer",
    "buyerPhone",
    "scheduledReceiptDate",
    "vendorCode",
    "transferWarehouseCode",
    "originalOrderNo",
    "note",
    "receiptMode",
    "licensePlateNumber",
    "driver",
    "tradePlatform",
    "tradeOrder",
    "driverCalls",
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8",
    "items"
})
@XmlRootElement(name = "PurchaseOrder")
public class InboundReqPurchaseOrder {

    @XmlElement(name = "WarehouseCode", required = true)
    protected String warehouseCode;
    @XmlElement(name = "ErpOrder", required = true)
    protected String erpOrder;
    @XmlElement(name = "ErpOrderType", required = true)
    protected String erpOrderType;
    @XmlElement(name = "SFOrderType", required = true)
    protected String sfOrderType;
    @XmlElement(name = "OrderDate", required = true)
    protected String orderDate;
    @XmlElement(name = "Buyer", required = false)
    protected String buyer;
    @XmlElement(name = "BuyerPhone", required = false)
    protected String buyerPhone;
    @XmlElement(name = "ScheduledReceiptDate", required = true)
    protected String scheduledReceiptDate;
    @XmlElement(name = "VendorCode", required = true)
    protected String vendorCode;
    @XmlElement(name = "TransferWarehouseCode", required = false)
    protected String transferWarehouseCode;
    @XmlElement(name = "OriginalOrderNo", required = false)
    protected String originalOrderNo;
    @XmlElement(name = "Note", required = true)
    protected String note;
    @XmlElement(name = "ReceiptMode", required = true)
    protected String receiptMode;
    @XmlElement(name = "LicensePlateNumber", required = false)
    protected String licensePlateNumber;
    @XmlElement(name = "Driver", required = false)
    protected String driver;
    @XmlElement(name = "TradePlatform", required = false)
    protected String tradePlatform;
    @XmlElement(name = "TradeOrder", required = false)
    protected String tradeOrder;
    @XmlElement(name = "DriverCalls", required = false)
    protected String driverCalls;
    @XmlElement(name = "UserDef1", required = false)
    protected String userDef1;
    @XmlElement(name = "UserDef2", required = false)
    protected String userDef2;
    @XmlElement(name = "UserDef3", required = false)
    protected String userDef3;
    @XmlElement(name = "UserDef4", required = false)
    protected String userDef4;
    @XmlElement(name = "UserDef5", required = false)
    protected String userDef5;
    @XmlElement(name = "UserDef6", required = false)
    protected String userDef6;
    @XmlElement(name = "UserDef7", required = false)
    protected String userDef7;
    @XmlElement(name = "UserDef8", required = false)
    protected String userDef8;
    @XmlElement(name = "Items", required = false)
    protected InboundReqItems items;

    /**
     * Gets the value of the warehouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * Sets the value of the warehouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseCode(String value) {
        this.warehouseCode = value;
    }

    /**
     * Gets the value of the erpOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErpOrder() {
        return erpOrder;
    }

    /**
     * Sets the value of the erpOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErpOrder(String value) {
        this.erpOrder = value;
    }

    /**
     * Gets the value of the erpOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErpOrderType() {
        return erpOrderType;
    }

    /**
     * Sets the value of the erpOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErpOrderType(String value) {
        this.erpOrderType = value;
    }

    /**
     * Gets the value of the sfOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFOrderType() {
        return sfOrderType;
    }

    /**
     * Sets the value of the sfOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFOrderType(String value) {
        this.sfOrderType = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }
    
    /**
     * Gets the value of the buyer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyer(String value) {
        this.buyer = value;
    }

    /**
     * Gets the value of the buyerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerPhone() {
        return buyerPhone;
    }

    /**
     * Sets the value of the buyerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerPhone(String value) {
        this.buyerPhone = value;
    }

    /**
     * Gets the value of the scheduledReceiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduledReceiptDate() {
        return scheduledReceiptDate;
    }

    /**
     * Sets the value of the scheduledReceiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduledReceiptDate(String value) {
        this.scheduledReceiptDate = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }
    
    /**
     * Gets the value of the transferWarehouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferWarehouseCode() {
        return transferWarehouseCode;
    }

    /**
     * Sets the value of the transferWarehouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferWarehouseCode(String value) {
        this.transferWarehouseCode = value;
    }

    /**
     * Gets the value of the originalOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalOrderNo() {
        return originalOrderNo;
    }

    /**
     * Sets the value of the originalOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalOrderNo(String value) {
        this.originalOrderNo = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the receiptMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptMode() {
        return receiptMode;
    }

    /**
     * Sets the value of the receiptMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptMode(String value) {
        this.receiptMode = value;
    }

    /**
     * Gets the value of the licensePlateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicensePlateNumber() {
        return licensePlateNumber;
    }

    /**
     * Sets the value of the licensePlateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicensePlateNumber(String value) {
        this.licensePlateNumber = value;
    }

    /**
     * Gets the value of the driver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriver() {
        return driver;
    }

    /**
     * Sets the value of the driver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriver(String value) {
        this.driver = value;
    }

    /**
     * Gets the value of the tradePlatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradePlatform() {
        return tradePlatform;
    }

    /**
     * Sets the value of the tradePlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradePlatform(String value) {
        this.tradePlatform = value;
    }

    /**
     * Gets the value of the tradeOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeOrder() {
        return tradeOrder;
    }

    /**
     * Sets the value of the tradeOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeOrder(String value) {
        this.tradeOrder = value;
    }

    /**
     * Gets the value of the driverCalls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverCalls() {
        return driverCalls;
    }

    /**
     * Sets the value of the driverCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverCalls(String value) {
        this.driverCalls = value;
    }

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link InboundReqItems }
     *     
     */
    public InboundReqItems getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundReqItems }
     *     
     */
    public void setItems(InboundReqItems value) {
        this.items = value;
    }

}
