//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.20 at 03:24:23 PM CST
//

package com.jumbo.webservice.outsourcingWH.command;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batchId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ro" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trackingNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="roLine" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"batchId", "totalQty", "source", "ro"})
@XmlRootElement(name = "roList")
public class RoList implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2954757014066607625L;
    @XmlElement(required = true)
    protected String batchId = "";
    @XmlElement(required = true)
    protected String totalQty = "";
    @XmlElement(required = true)
    protected String source = "";
    @XmlElement(required = true)
    protected List<RoList.Ro> ro;

    /**
     * Gets the value of the batchId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBatchId(String value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the totalQty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalQty() {
        return totalQty;
    }

    /**
     * Sets the value of the totalQty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTotalQty(String value) {
        this.totalQty = value;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Gets the value of the ro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the ro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
	 * getRo().add(newItem);
	 * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RoList.Ro }
     * 
     * 
     */
    public List<RoList.Ro> getRo() {
        if (ro == null) {
            ro = new ArrayList<RoList.Ro>();
        }
        return this.ro;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="logistic" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="trackingNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="roLine" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"code", "plfCode", "storeCode", "logistic", "trackingNo", "receiver", "telephone", "mobile", "createTime", "roLine"})
    public static class Ro implements Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = -6752186113272181698L;
		@XmlElement(required = true)
        protected String code = "";
        @XmlElement(required = true)
        protected String plfCode = "";
        @XmlElement(required = true)
        protected String storeCode = "";
        @XmlElement(required = true)
        protected String logistic = "";
        @XmlElement(required = true)
        protected String trackingNo = "";
        @XmlElement(required = true)
        protected String receiver = "";
        @XmlElement(required = true)
        protected String telephone = "";
        @XmlElement(required = true)
        protected String mobile = "";
        @XmlElement(required = true)
        protected String createTime = "";
        @XmlElement(required = true)
        protected List<RoList.Ro.RoLine> roLine;

        /**
         * Gets the value of the code property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the plfCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPlfCode() {
            return plfCode;
        }

        /**
         * Sets the value of the plfCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setPlfCode(String value) {
            this.plfCode = value;
        }

        /**
         * Gets the value of the storeCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getStoreCode() {
            return storeCode;
        }

        /**
         * Sets the value of the storeCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setStoreCode(String value) {
            this.storeCode = value;
        }

        /**
         * Gets the value of the logistic property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLogistic() {
            return logistic;
        }

        /**
         * Sets the value of the logistic property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLogistic(String value) {
            this.logistic = value;
        }

        /**
         * Gets the value of the trackingNo property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTrackingNo() {
            return trackingNo;
        }

        /**
         * Sets the value of the trackingNo property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTrackingNo(String value) {
            this.trackingNo = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getReceiver() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setReceiver(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the mobile property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getMobile() {
            return mobile;
        }

        /**
         * Sets the value of the mobile property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setMobile(String value) {
            this.mobile = value;
        }

        /**
         * Gets the value of the createTime property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCreateTime() {
            return createTime;
        }

        /**
         * Sets the value of the createTime property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCreateTime(String value) {
            this.createTime = value;
        }

        /**
         * Gets the value of the roLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the roLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
		 * getRoLine().add(newItem);
		 * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link RoList.Ro.RoLine }
         * 
         * 
         */
        public List<RoList.Ro.RoLine> getRoLine() {
            if (roLine == null) {
                roLine = new ArrayList<RoList.Ro.RoLine>();
            }
            return this.roLine;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"sku", "bzskuCode", "barcode", "quantity"})
        public static class RoLine implements Serializable {

            /**
			 * 
			 */
			private static final long serialVersionUID = 9196627864966936379L;
			@XmlElement(required = true)
            protected String sku = "";
            @XmlElement(required = true)
            protected String bzskuCode = "";
            @XmlElement(required = true)
            protected String barcode = "";
            @XmlElement(required = true)
            protected String quantity = "";

            /**
             * Gets the value of the sku property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getSku() {
                return sku;
            }

            /**
             * Sets the value of the sku property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setSku(String value) {
                this.sku = value;
            }

            /**
             * Gets the value of the bzskuCode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBzskuCode() {
                return bzskuCode;
            }

            /**
             * Sets the value of the bzskuCode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBzskuCode(String value) {
                this.bzskuCode = value;
            }

            /**
             * Gets the value of the barcode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBarcode() {
                return barcode;
            }

            /**
             * Sets the value of the barcode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBarcode(String value) {
                this.barcode = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

        }

    }

}
