//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.05 at 04:51:55 ���� CST
//


package com.jumbo.webservice.outsourcingWH.command;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batchId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sta" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="staLine" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"batchId", "totalQty", "source", "sta"})
@XmlRootElement(name = "StaList")
public class StaList implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4683290459404489243L;
    @XmlElement(required = true)
    protected String batchId;
    @XmlElement(required = true)
    protected String totalQty;
    @XmlElement(required = true)
    protected String source = "";
    @XmlElement(required = true)
    protected List<StaList.Sta> sta;

    /**
     * Gets the value of the batchId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBatchId(String value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the totalQty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalQty() {
        return totalQty;
    }

    /**
     * Sets the value of the totalQty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTotalQty(String value) {
        this.totalQty = value;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Gets the value of the sta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the sta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     *    getSta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link StaList.Sta }
     * 
     * 
     */
    public List<StaList.Sta> getSta() {
        if (sta == null) {
            sta = new ArrayList<StaList.Sta>();
        }
        return this.sta;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="plfCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="storeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="staLine" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"code", "plfCode", "storeCode", "createTime", "staLine"})
    public static class Sta implements Serializable {

        /**
         * 
         */
        private static final long serialVersionUID = -7709032460955192033L;
        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String plfCode;
        @XmlElement(required = true)
        protected String storeCode;
        @XmlElement(required = true)
        protected String createTime;
        @XmlElement(required = true)
        protected List<StaList.Sta.StaLine> staLine;

        /**
         * Gets the value of the code property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the plfCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPlfCode() {
            return plfCode;
        }

        /**
         * Sets the value of the plfCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setPlfCode(String value) {
            this.plfCode = value;
        }

        /**
         * Gets the value of the storeCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getStoreCode() {
            return storeCode;
        }

        /**
         * Sets the value of the storeCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setStoreCode(String value) {
            this.storeCode = value;
        }

        /**
         * Gets the value of the createTime property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCreateTime() {
            return createTime;
        }

        /**
         * Sets the value of the createTime property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCreateTime(String value) {
            this.createTime = value;
        }

        /**
         * Gets the value of the staLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the staLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         *    getStaLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link StaList.Sta.StaLine }
         * 
         * 
         */
        public List<StaList.Sta.StaLine> getStaLine() {
            if (staLine == null) {
                staLine = new ArrayList<StaList.Sta.StaLine>();
            }
            return this.staLine;
        }


        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="bzskuCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"sku", "bzskuCode", "barcode", "quantity"})
        public static class StaLine implements Serializable {

            /**
             * 
             */
            private static final long serialVersionUID = -5637214702134909184L;
            @XmlElement(required = true)
            protected String sku;
            @XmlElement(required = true)
            protected String bzskuCode;
            @XmlElement(required = true)
            protected String barcode;
            @XmlElement(required = true)
            protected String quantity;

            /**
             * Gets the value of the sku property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getSku() {
                return sku;
            }

            /**
             * Sets the value of the sku property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setSku(String value) {
                this.sku = value;
            }

            /**
             * Gets the value of the bzskuCode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBzskuCode() {
                return bzskuCode;
            }

            /**
             * Sets the value of the bzskuCode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBzskuCode(String value) {
                this.bzskuCode = value;
            }

            /**
             * Gets the value of the barcode property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getBarcode() {
                return barcode;
            }

            /**
             * Sets the value of the barcode property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setBarcode(String value) {
                this.barcode = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

        }

    }

}
