package com.jumbo.webservice.base;

import java.io.Serializable;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4 2013-04-19T13:40:34.957+08:00 Generated source
 * version: 2.7.4
 */

@WebFault(name = "authenticationFailed", targetNamespace = "http://webservice.jumbo.com/pda/")
public class AuthenticationFailedException extends Exception implements Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = -2844781114556791853L;
    private com.jumbo.webservice.base.AuthenticationFailed authenticationFailed;

    public AuthenticationFailedException() {
        super();
    }

    public AuthenticationFailedException(String message) {
        super(message);
    }

    public AuthenticationFailedException(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthenticationFailedException(String message, com.jumbo.webservice.base.AuthenticationFailed authenticationFailed) {
        super(message);
        this.authenticationFailed = authenticationFailed;
    }

    public AuthenticationFailedException(String message, com.jumbo.webservice.base.AuthenticationFailed authenticationFailed, Throwable cause) {
        super(message, cause);
        this.authenticationFailed = authenticationFailed;
    }

    public com.jumbo.webservice.base.AuthenticationFailed getFaultInfo() {
        return this.authenticationFailed;
    }
}
