
package com.jumbo.wms.webservice.pda;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jun 08 16:08:23 CST 2015
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "authenticationFailed", targetNamespace = "http://webservice.jumbo.com/pda/")
public class AuthenticationFailedException extends Exception {
    public static final long serialVersionUID = 20150608160823L;
    
    private com.jumbo.wms.webservice.pda.AuthenticationFailed authenticationFailed;

    public AuthenticationFailedException() {
        super();
    }
    
    public AuthenticationFailedException(String message) {
        super(message);
    }
    
    public AuthenticationFailedException(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthenticationFailedException(String message, com.jumbo.wms.webservice.pda.AuthenticationFailed authenticationFailed) {
        super(message);
        this.authenticationFailed = authenticationFailed;
    }

    public AuthenticationFailedException(String message, com.jumbo.wms.webservice.pda.AuthenticationFailed authenticationFailed, Throwable cause) {
        super(message, cause);
        this.authenticationFailed = authenticationFailed;
    }

    public com.jumbo.wms.webservice.pda.AuthenticationFailed getFaultInfo() {
        return this.authenticationFailed;
    }
}
