
package com.jumbo.wms.webservice.pda;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jun 08 16:08:23 CST 2015
 * Generated source version: 2.2.9
 * 
 */

public final class PdaService_PdaServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.jumbo.com/pda/", "PdaServiceService");

    private PdaService_PdaServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PdaServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            }
        }
      
        PdaServiceService ss = new PdaServiceService(wsdlURL, SERVICE_NAME);
        PdaService port = ss.getPdaServicePort();  
        
        {
        System.out.println("Invoking uploadInventoryCheck...");
        com.jumbo.wms.webservice.pda.UploadInventoryCheckRequest _uploadInventoryCheck_uploadInventoryCheckRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadInventoryCheckResponse _uploadInventoryCheck__return = port.uploadInventoryCheck(_uploadInventoryCheck_uploadInventoryCheckRequest);
            System.out.println("uploadInventoryCheck.result=" + _uploadInventoryCheck__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        com.jumbo.wms.webservice.pda.LoginRequest _login_loginRequest = null;
        try {
            com.jumbo.wms.webservice.pda.LoginResponse _login__return = port.login(_login_loginRequest);
            System.out.println("login.result=" + _login__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadLibraryMovement...");
        com.jumbo.wms.webservice.pda.UploadLibraryMovementRequest _uploadLibraryMovement_uploadLibraryMovementRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadLibraryMovementResponse _uploadLibraryMovement__return = port.uploadLibraryMovement(_uploadLibraryMovement_uploadLibraryMovementRequest);
            System.out.println("uploadLibraryMovement.result=" + _uploadLibraryMovement__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadInitiativeMoveOutbound...");
        com.jumbo.wms.webservice.pda.UploadInitiativeMoveOutboundRequest _uploadInitiativeMoveOutbound_uploadInitiativeMoveOutboundRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadInitiativeMoveOutboundResponse _uploadInitiativeMoveOutbound__return = port.uploadInitiativeMoveOutbound(_uploadInitiativeMoveOutbound_uploadInitiativeMoveOutboundRequest);
            System.out.println("uploadInitiativeMoveOutbound.result=" + _uploadInitiativeMoveOutbound__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadReturnOrder...");
        com.jumbo.wms.webservice.pda.UploadReturnOrderRequest _uploadReturnOrder_uploadReturnOrderRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadReturnOrderResponse _uploadReturnOrder__return = port.uploadReturnOrder(_uploadReturnOrder_uploadReturnOrderRequest);
            System.out.println("uploadReturnOrder.result=" + _uploadReturnOrder__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getInventoryCheck...");
        com.jumbo.wms.webservice.pda.GetInventoryCheckRequest _getInventoryCheck_getInventoryCheckRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetInventoryCheckResponse _getInventoryCheck__return = port.getInventoryCheck(_getInventoryCheck_getInventoryCheckRequest);
            System.out.println("getInventoryCheck.result=" + _getInventoryCheck__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSku...");
        com.jumbo.wms.webservice.pda.GetSkuRequest _getSku_getSkuRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetSkuResponse _getSku__return = port.getSku(_getSku_getSkuRequest);
            System.out.println("getSku.result=" + _getSku__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadPickingOutbound...");
        com.jumbo.wms.webservice.pda.UploadPickingOutboundRequest _uploadPickingOutbound_uploadPickingOutboundRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadPickingOutboundResponse _uploadPickingOutbound__return = port.uploadPickingOutbound(_uploadPickingOutbound_uploadPickingOutboundRequest);
            System.out.println("uploadPickingOutbound.result=" + _uploadPickingOutbound__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getInboundOnShelves...");
        com.jumbo.wms.webservice.pda.GetInboundOnShelvesRequest _getInboundOnShelves_getInboundOnShelvesRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetInboundOnShelvesResponse _getInboundOnShelves__return = port.getInboundOnShelves(_getInboundOnShelves_getInboundOnShelvesRequest);
            System.out.println("getInboundOnShelves.result=" + _getInboundOnShelves__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadInboundReceive...");
        com.jumbo.wms.webservice.pda.UploadInboundReceiveRequest _uploadInboundReceive_uploadInboundReceiveRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadInboundReceiveResponse _uploadInboundReceive__return = port.uploadInboundReceive(_uploadInboundReceive_uploadInboundReceiveRequest);
            System.out.println("uploadInboundReceive.result=" + _uploadInboundReceive__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking executeOrder...");
        com.jumbo.wms.webservice.pda.ExecuteOrderRequest _executeOrder_executeOrderRequest = null;
        try {
            com.jumbo.wms.webservice.pda.ExecuteOrderResponse _executeOrder__return = port.executeOrder(_executeOrder_executeOrderRequest);
            System.out.println("executeOrder.result=" + _executeOrder__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getInboundData...");
        com.jumbo.wms.webservice.pda.GetInboundDataRequest _getInboundData_getInboundDataRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetInboundDataResponse _getInboundData__return = port.getInboundData(_getInboundData_getInboundDataRequest);
            System.out.println("getInboundData.result=" + _getInboundData__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getReturnOrder...");
        com.jumbo.wms.webservice.pda.GetReturnOrderRequest _getReturnOrder_getReturnOrderRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetReturnOrderResponse _getReturnOrder__return = port.getReturnOrder(_getReturnOrder_getReturnOrderRequest);
            System.out.println("getReturnOrder.result=" + _getReturnOrder__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadHandOverList...");
        com.jumbo.wms.webservice.pda.UploadHandOverListRequest _uploadHandOverList_uploadHandOverListRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadHandOverListResponse _uploadHandOverList__return = port.uploadHandOverList(_uploadHandOverList_uploadHandOverListRequest);
            System.out.println("uploadHandOverList.result=" + _uploadHandOverList__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadInitiativeMoveInbound...");
        com.jumbo.wms.webservice.pda.UploadInitiativeMoveInboundRequest _uploadInitiativeMoveInbound_uploadInitiativeMoveInboundRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadInitiativeMoveInboundResponse _uploadInitiativeMoveInbound__return = port.uploadInitiativeMoveInbound(_uploadInitiativeMoveInbound_uploadInitiativeMoveInboundRequest);
            System.out.println("uploadInitiativeMoveInbound.result=" + _uploadInitiativeMoveInbound__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getWarehouses...");
        com.jumbo.wms.webservice.pda.GetWarehousesRequest _getWarehouses_getWarehousesRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetWarehousesResponse _getWarehouses__return = port.getWarehouses(_getWarehouses_getWarehousesRequest);
            System.out.println("getWarehouses.result=" + _getWarehouses__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadInboundOnShelves...");
        com.jumbo.wms.webservice.pda.UploadInboundOnShelvesRequest _uploadInboundOnShelves_uploadInboundOnShelvesRequest = null;
        try {
            com.jumbo.wms.webservice.pda.UploadInboundOnShelvesResponse _uploadInboundOnShelves__return = port.uploadInboundOnShelves(_uploadInboundOnShelves_uploadInboundOnShelvesRequest);
            System.out.println("uploadInboundOnShelves.result=" + _uploadInboundOnShelves__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getLibraryMovement...");
        com.jumbo.wms.webservice.pda.GetLibraryMovementRequest _getLibraryMovement_getLibraryMovementRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetLibraryMovementResponse _getLibraryMovement__return = port.getLibraryMovement(_getLibraryMovement_getLibraryMovementRequest);
            System.out.println("getLibraryMovement.result=" + _getLibraryMovement__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransNo...");
        com.jumbo.wms.webservice.pda.GetTransNoRequest _getTransNo_getTransNoRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetTransNoResponse _getTransNo__return = port.getTransNo(_getTransNo_getTransNoRequest);
            System.out.println("getTransNo.result=" + _getTransNo__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getInventory...");
        com.jumbo.wms.webservice.pda.GetInventoryRequest _getInventory_getInventoryRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetInventoryResponse _getInventory__return = port.getInventory(_getInventory_getInventoryRequest);
            System.out.println("getInventory.result=" + _getInventory__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPickingData...");
        com.jumbo.wms.webservice.pda.GetPickingDataRequest _getPickingData_getPickingDataRequest = null;
        try {
            com.jumbo.wms.webservice.pda.GetPickingDataResponse _getPickingData__return = port.getPickingData(_getPickingData_getPickingDataRequest);
            System.out.println("getPickingData.result=" + _getPickingData__return);

        } catch (AuthenticationFailedException e) { 
            System.out.println("Expected exception: AuthenticationFailedException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
