/*
 * 
 */

package com.jumbo.wms.webservice.pda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9 Mon Jun 08 16:08:23 CST 2015 Generated source
 * version: 2.2.9
 * 
 */


@WebServiceClient(name = "PdaServiceService", wsdlLocation = "http://localhost:8001/scm/webservice/pda?wsdl", targetNamespace = "http://webservice.jumbo.com/pda/")
public class PdaServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.jumbo.com/pda/", "PdaServiceService");
    public final static QName PdaServicePort = new QName("http://webservice.jumbo.com/pda/", "PdaServicePort");
    static {
        URL url = null;
        try {
            String surl = "http://uat.scm.baozun.cn/scm/webservice/pda?wsdl";
            System.out.println("check system is url is :" + surl);
            url = new URL(surl);
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8001/scm/webservice/pda?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PdaServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PdaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PdaServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * 
     * @return returns PdaService
     */
    @WebEndpoint(name = "PdaServicePort")
    public PdaService getPdaServicePort() {
        return super.getPort(PdaServicePort, PdaService.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *        Supported features not in the <code>features</code> parameter will have their default
     *        values.
     * @return returns PdaService
     */
    @WebEndpoint(name = "PdaServicePort")
    public PdaService getPdaServicePort(WebServiceFeature... features) {
        return super.getPort(PdaServicePort, PdaService.class, features);
    }

}
