/*
 * 
 */

package com.jumbo.webservice.sf;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by Apache CXF 2.2.9 Fri Dec 21 10:50:40 CST 2012 Generated source
 * version: 2.2.9
 * 
 */


@WebServiceClient(name = "CustomerServiceService", wsdlLocation = "http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl", targetNamespace = "http://service.serviceprovide.module.sf.com/")
public class CustomerServiceService extends Service implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 9013457635826193230L;
    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.serviceprovide.module.sf.com/", "CustomerServiceService");
    public final static QName CustomerServicePort = new QName("http://service.serviceprovide.module.sf.com/", "CustomerServicePort");
    static {
        URL url = null;
        try {
            // url = new URL("http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl");
            url = new URL(CustomerServiceService.class.getResource("/") + "wsdl/sf.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl");
            // log.error("",e);
        }
        WSDL_LOCATION = url;
    }

    public CustomerServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * 
     * @return returns ICustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public ICustomerService getCustomerServicePort() {
        return super.getPort(CustomerServicePort, ICustomerService.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *        Supported features not in the <code>features</code> parameter will have their default
     *        values.
     * @return returns ICustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public ICustomerService getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerServicePort, ICustomerService.class, features);
    }

}
