package com.bt.orderPlatform.controller.form;

import com.bt.orderPlatform.page.QueryParameter;

public class ExpressinfoMasterInputlistQueryParam extends QueryParameter {
	
		private Integer id;			//	private String bat_id;			//	private java.util.Date create_time;			//	private String create_user;			//	private java.util.Date update_time;			//	private String upddate_user;			//	private Integer success_num;			//	private Integer fail_num;			//	private Integer total_num;			//	private Integer flag;			//0 为初始状态 1：转换过状态	public Integer getId() {	    return this.id;	}	public void setId(Integer id) {	    this.id=id;	}	public String getBat_id() {	    return this.bat_id;	}	public void setBat_id(String bat_id) {	    this.bat_id=bat_id;	}	public java.util.Date getCreate_time() {	    return this.create_time;	}	public void setCreate_time(java.util.Date create_time) {	    this.create_time=create_time;	}	public String getCreate_user() {	    return this.create_user;	}	public void setCreate_user(String create_user) {	    this.create_user=create_user;	}	public java.util.Date getUpdate_time() {	    return this.update_time;	}	public void setUpdate_time(java.util.Date update_time) {	    this.update_time=update_time;	}	public String getUpddate_user() {	    return this.upddate_user;	}	public void setUpddate_user(String upddate_user) {	    this.upddate_user=upddate_user;	}	public Integer getSuccess_num() {	    return this.success_num;	}	public void setSuccess_num(Integer success_num) {	    this.success_num=success_num;	}	public Integer getFail_num() {	    return this.fail_num;	}	public void setFail_num(Integer fail_num) {	    this.fail_num=fail_num;	}	public Integer getTotal_num() {	    return this.total_num;	}	public void setTotal_num(Integer total_num) {	    this.total_num=total_num;	}	public Integer getFlag() {	    return this.flag;	}	public void setFlag(Integer flag) {	    this.flag=flag;	}
	
}
