package com.bt.lmis.model;

/**
* @ClassName: NvitationdataCollect
* @Description: TODO(NvitationdataCollect)
* @author Yuriy.Jiang
* @date 2016年6月22日 上午10:19:25
*
*/
public class NvitationdataCollect {
	
		private Integer id;			//主键	private java.util.Date create_time;			//创建时间	private String create_user;			//创建人	private java.util.Date update_time;			//更新时间	private String update_user;			//更新人	private Integer contract_id;			//合同id	private String billing_cycle;			//账单周期	private String sku_type;			//耗材类型(主材；辅材)	private java.math.BigDecimal qty;			//数量	private String qty_unit;			//数量单位	private java.math.BigDecimal fee;			//单价	private String fee_unit;			//单价单位	private java.math.BigDecimal total_amount;			//总金额	private String totalamount_unit;			//总金额单位	public Integer getId() {	    return this.id;	}	public void setId(Integer id) {	    this.id=id;	}	public java.util.Date getCreate_time() {	    return this.create_time;	}	public void setCreate_time(java.util.Date create_time) {	    this.create_time=create_time;	}	public String getCreate_user() {	    return this.create_user;	}	public void setCreate_user(String create_user) {	    this.create_user=create_user;	}	public java.util.Date getUpdate_time() {	    return this.update_time;	}	public void setUpdate_time(java.util.Date update_time) {	    this.update_time=update_time;	}	public String getUpdate_user() {	    return this.update_user;	}	public void setUpdate_user(String update_user) {	    this.update_user=update_user;	}	public Integer getContract_id() {	    return this.contract_id;	}	public void setContract_id(Integer contract_id) {	    this.contract_id=contract_id;	}	public String getBilling_cycle() {	    return this.billing_cycle;	}	public void setBilling_cycle(String billing_cycle) {	    this.billing_cycle=billing_cycle;	}	public String getSku_type() {	    return this.sku_type;	}	public void setSku_type(String sku_type) {	    this.sku_type=sku_type;	}	public java.math.BigDecimal getQty() {	    return this.qty;	}	public void setQty(java.math.BigDecimal qty) {	    this.qty=qty;	}	public String getQty_unit() {	    return this.qty_unit;	}	public void setQty_unit(String qty_unit) {	    this.qty_unit=qty_unit;	}	public java.math.BigDecimal getFee() {	    return this.fee;	}	public void setFee(java.math.BigDecimal fee) {	    this.fee=fee;	}	public String getFee_unit() {	    return this.fee_unit;	}	public void setFee_unit(String fee_unit) {	    this.fee_unit=fee_unit;	}	public java.math.BigDecimal getTotal_amount() {	    return this.total_amount;	}	public void setTotal_amount(java.math.BigDecimal total_amount) {	    this.total_amount=total_amount;	}	public String getTotalamount_unit() {	    return this.totalamount_unit;	}	public void setTotalamount_unit(String totalamount_unit) {	    this.totalamount_unit=totalamount_unit;	}
}
