package com.jumbo.webservice.biaogan.client.base;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2 2012-03-19T12:59:29.353+08:00 Generated source
 * version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://server.webservices.chamayi.chamago.com", name = "PushExpressInfoPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PushExpressInfoPortType {

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "searchOrderStatus", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchOrderStatus")
    @WebMethod
    @ResponseWrapper(localName = "searchOrderStatusResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchOrderStatusResponse")
    public com.jumbo.webservice.biaogan.client.base.WmsResultInfoToERP searchOrderStatus(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "searchWarehouse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchWarehouse")
    @WebMethod
    @ResponseWrapper(localName = "searchWarehouseResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchWarehouseResponse")
    public com.jumbo.webservice.biaogan.client.base.ArrayOfWmsSPRecord searchWarehouse();

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "PutSOFromWMS", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutSOFromWMS")
    @WebMethod(operationName = "PutSOFromWMS")
    @ResponseWrapper(localName = "PutSOFromWMSResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutSOFromWMSResponse")
    public com.jumbo.webservice.biaogan.client.base.WmsResultInfoToERP putSOFromWMS(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") com.jumbo.webservice.biaogan.client.base.IdxSoTransaction in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "soToWms", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SoToWms")
    @WebMethod
    @ResponseWrapper(localName = "soToWmsResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SoToWmsResponse")
    public java.lang.String soToWms(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "searchWarehouseBySkuId", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchWarehouseBySkuId")
    @WebMethod
    @ResponseWrapper(localName = "searchWarehouseBySkuIdResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SearchWarehouseBySkuIdResponse")
    public com.jumbo.webservice.biaogan.client.base.ArrayOfWmsSPRecord searchWarehouseBySkuId(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "putANSFormWms", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutANSFormWms")
    @WebMethod
    @ResponseWrapper(localName = "putANSFormWmsResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutANSFormWmsResponse")
    public com.jumbo.webservice.biaogan.client.base.WmsResultInfoToERP putANSFormWms(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") com.jumbo.webservice.biaogan.client.base.CmerpInputFromBg in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "ansToWms", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.AnsToWms")
    @WebMethod
    @ResponseWrapper(localName = "ansToWmsResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.AnsToWmsResponse")
    public java.lang.String ansToWms(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "putInventoryAdjustment", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutInventoryAdjustment")
    @WebMethod
    @ResponseWrapper(localName = "putInventoryAdjustmentResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.PutInventoryAdjustmentResponse")
    public com.jumbo.webservice.biaogan.client.base.WmsResultInfoToERP putInventoryAdjustment(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") com.jumbo.webservice.biaogan.client.base.InventoryAdjustment in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "singleSkuToWms", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SingleSkuToWms")
    @WebMethod
    @ResponseWrapper(localName = "singleSkuToWmsResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.SingleSkuToWmsResponse")
    public java.lang.String singleSkuToWms(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "moreSkuToWms", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.MoreSkuToWms")
    @WebMethod
    @ResponseWrapper(localName = "moreSkuToWmsResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.MoreSkuToWmsResponse")
    public java.lang.String moreSkuToWms(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);

    @WebResult(name = "out", targetNamespace = "http://server.webservices.chamayi.chamago.com")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.CancelOrder")
    @WebMethod
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://server.webservices.chamayi.chamago.com", className = "com.jumbo.webservice.biaogan.CancelOrderResponse")
    public java.lang.String cancelOrder(@WebParam(name = "in0", targetNamespace = "http://server.webservices.chamayi.chamago.com") java.lang.String in0);
}
