package com.jumbo.webservice.biaogan.clientNew.base;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9 Wed May 23 15:15:09 CST 2012 Generated source
 * version: 2.2.9
 * 
 */

@WebService(targetNamespace = "http://BML", name = "BMLQueryPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BMLQueryPortType {

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "OrderCollectionYesterday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderCollectionYesterday")
    @WebMethod(operationName = "OrderCollectionYesterday")
    @ResponseWrapper(localName = "OrderCollectionYesterdayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderCollectionYesterdayResponse")
    public java.lang.String orderCollectionYesterday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "soToWmsbyPage", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SoToWmsbyPage")
    @WebMethod
    @ResponseWrapper(localName = "soToWmsbyPageResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SoToWmsbyPageResponse")
    public java.lang.String soToWmsbyPage(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "searchOrderStatus", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SearchOrderStatus")
    @WebMethod
    @ResponseWrapper(localName = "searchOrderStatusResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SearchOrderStatusResponse")
    public java.lang.String searchOrderStatus(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "UrgentOrderBySoNo", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.UrgentOrderBySoNo")
    @WebMethod(operationName = "UrgentOrderBySoNo")
    @ResponseWrapper(localName = "UrgentOrderBySoNoResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.UrgentOrderBySoNoResponse")
    public java.lang.String urgentOrderBySoNo(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "OrderDetailQueryToday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderDetailQueryToday")
    @WebMethod(operationName = "OrderDetailQueryToday")
    @ResponseWrapper(localName = "OrderDetailQueryTodayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderDetailQueryTodayResponse")
    public java.lang.String orderDetailQueryToday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "singleSkuToWms", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SingleSkuToWms")
    @WebMethod
    @ResponseWrapper(localName = "singleSkuToWmsResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.SingleSkuToWmsResponse")
    public java.lang.String singleSkuToWms(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "NoticeOfArrivalQueryYesterday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalQueryYesterday")
    @WebMethod(operationName = "NoticeOfArrivalQueryYesterday")
    @ResponseWrapper(localName = "NoticeOfArrivalQueryYesterdayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalQueryYesterdayResponse")
    public java.lang.String noticeOfArrivalQueryYesterday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "ansToWmsbyPage", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.AnsToWmsbyPage")
    @WebMethod
    @ResponseWrapper(localName = "ansToWmsbyPageResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.AnsToWmsbyPageResponse")
    public java.lang.String ansToWmsbyPage(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "AcceptEDIResult", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.AcceptEDIResult")
    @WebMethod(operationName = "AcceptEDIResult")
    @ResponseWrapper(localName = "AcceptEDIResultResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.AcceptEDIResultResponse")
    public java.lang.String acceptEDIResult(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "StockQuery", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.StockQuery")
    @WebMethod(operationName = "StockQuery")
    @ResponseWrapper(localName = "StockQueryResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.StockQueryResponse")
    public java.lang.String stockQuery(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "OrderCollectionToday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderCollectionToday")
    @WebMethod(operationName = "OrderCollectionToday")
    @ResponseWrapper(localName = "OrderCollectionTodayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderCollectionTodayResponse")
    public java.lang.String orderCollectionToday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "NoticeOfArrivalAssign", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalAssign")
    @WebMethod(operationName = "NoticeOfArrivalAssign")
    @ResponseWrapper(localName = "NoticeOfArrivalAssignResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalAssignResponse")
    public java.lang.String noticeOfArrivalAssign(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "cancelOrderRX", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderRX")
    @WebMethod
    @ResponseWrapper(localName = "cancelOrderRXResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderRXResponse")
    public java.lang.String cancelOrderRX(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "CancelOrderBySku", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderBySku")
    @WebMethod(operationName = "CancelOrderBySku")
    @ResponseWrapper(localName = "CancelOrderBySkuResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderBySkuResponse")
    public java.lang.String cancelOrderBySku(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2, @WebParam(name = "in3", targetNamespace = "http://BML") java.lang.String in3);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "OrderDetailQueryYesterday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderDetailQueryYesterday")
    @WebMethod(operationName = "OrderDetailQueryYesterday")
    @ResponseWrapper(localName = "OrderDetailQueryYesterdayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.OrderDetailQueryYesterdayResponse")
    public java.lang.String orderDetailQueryYesterday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "CancelOrderBySoNo", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderBySoNo")
    @WebMethod(operationName = "CancelOrderBySoNo")
    @ResponseWrapper(localName = "CancelOrderBySoNoResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.CancelOrderBySoNoResponse")
    public java.lang.String cancelOrderBySoNo(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "NoticeOfArrivalQueryToday", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalQueryToday")
    @WebMethod(operationName = "NoticeOfArrivalQueryToday")
    @ResponseWrapper(localName = "NoticeOfArrivalQueryTodayResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.NoticeOfArrivalQueryTodayResponse")
    public java.lang.String noticeOfArrivalQueryToday(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "StockQueryBySku", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.StockQueryBySku")
    @WebMethod(operationName = "StockQueryBySku")
    @ResponseWrapper(localName = "StockQueryBySkuResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.StockQueryBySkuResponse")
    public java.lang.String stockQueryBySku(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);

    @WebResult(name = "out", targetNamespace = "http://BML")
    @RequestWrapper(localName = "ShipmentInfoQueryByDate", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.ShipmentInfoQueryByDate")
    @WebMethod(operationName = "ShipmentInfoQueryByDate")
    @ResponseWrapper(localName = "ShipmentInfoQueryByDateResponse", targetNamespace = "http://BML", className = "com.jumbo.webservice.biaogan.clientNew.base.ShipmentInfoQueryByDateResponse")
    public java.lang.String shipmentInfoQueryByDate(@WebParam(name = "in0", targetNamespace = "http://BML") java.lang.String in0, @WebParam(name = "in1", targetNamespace = "http://BML") java.lang.String in1,
            @WebParam(name = "in2", targetNamespace = "http://BML") java.lang.String in2);
}
