//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 10:16:31 ���� CST 
//


package com.jumbo.webservice.sf.tw.sku.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PackUm"/>
 *         &lt;element ref="{}UmDescr"/>
 *         &lt;element ref="{}ConversionQty"/>
 *         &lt;element ref="{}Height"/>
 *         &lt;element ref="{}Width"/>
 *         &lt;element ref="{}Length"/>
 *         &lt;element ref="{}DimensionUm"/>
 *         &lt;element ref="{}Weight"/>
 *         &lt;element ref="{}WeightUm"/>
 *         &lt;element ref="{}UserDef1"/>
 *         &lt;element ref="{}UserDef2"/>
 *         &lt;element ref="{}UserDef3"/>
 *         &lt;element ref="{}UserDef4"/>
 *         &lt;element ref="{}UserDef5"/>
 *         &lt;element ref="{}UserDef6"/>
 *         &lt;element ref="{}UserDef7"/>
 *         &lt;element ref="{}UserDef8"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packUm",
    "umDescr",
    "conversionQty",
    "height",
    "width",
    "length",
    "dimensionUm",
    "weight",
    "weightUm",
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8"
})
@XmlRootElement(name = "Container")
public class Container {

    @XmlElement(name = "PackUm", required = false)
    protected String packUm;
    @XmlElement(name = "UmDescr", required = false)
    protected String umDescr;
    @XmlElement(name = "ConversionQty", required = false)
    protected String conversionQty;
    @XmlElement(name = "Height", required = false)
    protected String height;
    @XmlElement(name = "Width", required = false)
    protected String width;
    @XmlElement(name = "Length", required = false)
    protected String length;
    @XmlElement(name = "DimensionUm", required = false)
    protected String dimensionUm;
    @XmlElement(name = "Weight", required = false)
    protected String weight;
    @XmlElement(name = "WeightUm", required = false)
    protected String weightUm;
    @XmlElement(name = "UserDef1", required = false)
    protected String userDef1;
    @XmlElement(name = "UserDef2", required = false)
    protected String userDef2;
    @XmlElement(name = "UserDef3", required = false)
    protected String userDef3;
    @XmlElement(name = "UserDef4", required = false)
    protected String userDef4;
    @XmlElement(name = "UserDef5", required = false)
    protected String userDef5;
    @XmlElement(name = "UserDef6", required = false)
    protected String userDef6;
    @XmlElement(name = "UserDef7", required = false)
    protected String userDef7;
    @XmlElement(name = "UserDef8", required = false)
    protected String userDef8;

    /**
     * Gets the value of the packUm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackUm() {
        return packUm;
    }

    /**
     * Sets the value of the packUm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackUm(String value) {
        this.packUm = value;
    }

    /**
     * Gets the value of the umDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmDescr() {
        return umDescr;
    }

    /**
     * Sets the value of the umDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmDescr(String value) {
        this.umDescr = value;
    }

    /**
     * Gets the value of the conversionQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionQty() {
        return conversionQty;
    }

    /**
     * Sets the value of the conversionQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionQty(String value) {
        this.conversionQty = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the dimensionUm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimensionUm() {
        return dimensionUm;
    }

    /**
     * Sets the value of the dimensionUm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimensionUm(String value) {
        this.dimensionUm = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightUm() {
        return weightUm;
    }

    /**
     * Sets the value of the weightUm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightUm(String value) {
        this.weightUm = value;
    }

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

}
