//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 06:35:30 ���� CST 
//


package com.jumbo.webservice.sf.tw.sku.command;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jumbo.webservice.sf.tw.sku.command package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Result_QNAME = new QName("", "Result");
    private final static QName _Head_QNAME = new QName("", "Head");
    private final static QName _SkuNo_QNAME = new QName("", "SkuNo");
    private final static QName _Note_QNAME = new QName("", "Note");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jumbo.webservice.sf.tw.sku.command
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SkuRespItem }
     * 
     */
    public SkuRespItem createItem() {
        return new SkuRespItem();
    }

    /**
     * Create an instance of {@link SkuResponse }
     * 
     */
    public SkuResponse createResponse() {
        return new SkuResponse();
    }

    /**
     * Create an instance of {@link SkuRespItems }
     * 
     */
    public SkuRespItems createItems() {
        return new SkuRespItems();
    }

    /**
     * Create an instance of {@link SkuRespBody }
     * 
     */
    public SkuRespBody createBody() {
        return new SkuRespBody();
    }

    /**
     * Create an instance of {@link SkuItemResponse }
     * 
     */
    public SkuItemResponse createItemResponse() {
        return new SkuItemResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Result")
    public JAXBElement<String> createResult(String value) {
        return new JAXBElement<String>(_Result_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Head")
    public JAXBElement<String> createHead(String value) {
        return new JAXBElement<String>(_Head_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SkuNo")
    public JAXBElement<String> createSkuNo(String value) {
        return new JAXBElement<String>(_SkuNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Note")
    public JAXBElement<String> createNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, null, value);
    }

}
