//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 06:35:51 ���� CST 
//


package com.jumbo.webservice.sf.tw.sku.command;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DataId"/>
 *         &lt;element ref="{}ProcessTm"/>
 *         &lt;element ref="{}CreateEmp"/>
 *         &lt;element ref="{}SkuNo"/>
 *         &lt;element ref="{}ItemName"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}StandardDescription"/>
 *         &lt;element ref="{}Qc"/>
 *         &lt;element ref="{}Height"/>
 *         &lt;element ref="{}Width"/>
 *         &lt;element ref="{}Length"/>
 *         &lt;element ref="{}Weight"/>
 *         &lt;element ref="{}IsPresent"/>
 *         &lt;element ref="{}IsVirtualProduct"/>
 *         &lt;element ref="{}TransportProperty"/>
 *         &lt;element ref="{}IsFragile"/>
 *         &lt;element ref="{}ItemClass"/>
 *         &lt;element ref="{}ItemStyle"/>
 *         &lt;element ref="{}ItemColor"/>
 *         &lt;element ref="{}ItemSize"/>
 *         &lt;element ref="{}StorageTemperature"/>
 *         &lt;element ref="{}TransportTemperature"/>
 *         &lt;element ref="{}LotTemplate"/>
 *         &lt;element ref="{}SerialNumTrackInbound"/>
 *         &lt;element ref="{}SerialNumTrackOutbound"/>
 *         &lt;element ref="{}ItemClassify1"/>
 *         &lt;element ref="{}ItemClassify2"/>
 *         &lt;element ref="{}ItemClassify3"/>
 *         &lt;element ref="{}UserDef1"/>
 *         &lt;element ref="{}UserDef2"/>
 *         &lt;element ref="{}UserDef3"/>
 *         &lt;element ref="{}UserDef4"/>
 *         &lt;element ref="{}UserDef5"/>
 *         &lt;element ref="{}UserDef6"/>
 *         &lt;element ref="{}UserDef7"/>
 *         &lt;element ref="{}UserDef8"/>
 *         &lt;element ref="{}BarCode"/>
 *         &lt;element ref="{}ItemCategory"/>
 *         &lt;element ref="{}Containers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataId",
    "processTm",
    "createEmp",
    "skuNo",
    "itemName",
    "description",
    "standardDescription",
    "qc",
    "height",
    "width",
    "length",
    "weight",
    "qualityProportion",
    "isPresent",
    "isVirtualProduct",
    "transportProperty",
    "isFragile",
    "itemClass",
    "itemStyle",
    "itemColor",
    "itemSize",
    "storageTemperature",
    "transportTemperature",
    "expirationDateDays",
    "shelfLife",
    "qtymin",
    "lotTemplate",
    "serialNumTrackInbound",
    "serialNumTrackOutbound",
    "serialNumTrackInventory",
    "bomAction",
    "itemClassify1",
    "itemClassify2",
    "itemClassify3",
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8",
    "barCode",
    "itemCategory",
    "containers"
})
@XmlRootElement(name = "Item")
public class SkuReqItem {

    @XmlElement(name = "DataId", required = false)
    protected String dataId;
    @XmlElement(name = "ProcessTm", required = false)
    protected String processTm;
    @XmlElement(name = "CreateEmp", required = false)
    protected String createEmp;
    @XmlElement(name = "SkuNo", required = true)
    protected String skuNo;
    @XmlElement(name = "ItemName", required = true)
    protected String itemName;
    @XmlElement(name = "Description", required = false)
    protected String description;
    @XmlElement(name = "StandardDescription", required = false)
    protected StandardDescription standardDescription;
    @XmlElement(name = "Qc", required = false)
    protected Qc qc;
    @XmlElement(name = "Height", required = false)
    protected BigDecimal height;
    @XmlElement(name = "Width", required = false)
    protected BigDecimal width;
    @XmlElement(name = "Length", required = false)
    protected BigDecimal length;
    @XmlElement(name = "Weight", required = false)
    protected BigDecimal weight;
    @XmlElement(name = "QualityProportion", required = false)
    protected String qualityProportion;
    @XmlElement(name = "IsPresent", required = false)
    protected String isPresent;
    @XmlElement(name = "IsVirtualProduct", required = false)
    protected String isVirtualProduct;
    @XmlElement(name = "TransportProperty", required = false)
    protected String transportProperty;
    @XmlElement(name = "IsFragile", required = false)
    protected String isFragile;
    @XmlElement(name = "ItemClass", required = false)
    protected String itemClass;
    @XmlElement(name = "ItemStyle", required = false)
    protected String itemStyle;
    @XmlElement(name = "ItemColor", required = false)
    protected String itemColor;
    @XmlElement(name = "ItemSize", required = false)
    protected String itemSize;
    @XmlElement(name = "StorageTemperature", required = false)
    protected int storageTemperature;
    @XmlElement(name = "TransportTemperature", required = false)
    protected int transportTemperature;
    @XmlElement(name = "ExpirationDateDays", required = false)
    protected String expirationDateDays;
    @XmlElement(name = "ShelfLife", required = false)
    protected String shelfLife;
    @XmlElement(name = "Qtymin", required = false)
    protected String qtymin;
    @XmlElement(name = "LotTemplate", required = false)
    protected LotTemplate lotTemplate;
    @XmlElement(name = "SerialNumTrackInbound", required = false)
    protected String serialNumTrackInbound;
    @XmlElement(name = "SerialNumTrackOutbound", required = false)
    protected String serialNumTrackOutbound;
    @XmlElement(name = "SerialNumTrackInventory", required = false)
    protected String serialNumTrackInventory;
    @XmlElement(name = "BomAction", required = false)
    protected String bomAction;
    @XmlElement(name = "ItemClassify1", required = false)
    protected String itemClassify1;
    @XmlElement(name = "ItemClassify2", required = false)
    protected String itemClassify2;
    @XmlElement(name = "ItemClassify3", required = false)
    protected String itemClassify3;
    @XmlElement(name = "UserDef1", required = false)
    protected String userDef1;
    @XmlElement(name = "UserDef2", required = false)
    protected String userDef2;
    @XmlElement(name = "UserDef3", required = false)
    protected String userDef3;
    @XmlElement(name = "UserDef4", required = false)
    protected String userDef4;
    @XmlElement(name = "UserDef5", required = false)
    protected String userDef5;
    @XmlElement(name = "UserDef6", required = false)
    protected String userDef6;
    @XmlElement(name = "UserDef7", required = false)
    protected String userDef7;
    @XmlElement(name = "UserDef8", required = false)
    protected String userDef8;
    @XmlElement(name = "BarCode", required = true)
    protected SkuReqBarCode barCode;
    @XmlElement(name = "ItemCategory", required = true)
    protected SkuReqItemCategory itemCategory;
    @XmlElement(name = "Containers", required = true)
    protected Containers containers;

    
    /**
     * Gets the value of the dataId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * Sets the value of the dataId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataId(String value) {
        this.dataId = value;
    }

    /**
     * Gets the value of the processTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessTm() {
        return processTm;
    }

    /**
     * Sets the value of the processTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessTm(String value) {
        this.processTm = value;
    }

    /**
     * Gets the value of the createEmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * Sets the value of the createEmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateEmp(String value) {
        this.createEmp = value;
    }
    
    /**
     * Gets the value of the skuNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * Sets the value of the skuNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuNo(String value) {
        this.skuNo = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the standardDescription property.
     * 
     * @return
     *     possible object is
     *     {@link StandardDescription }
     *     
     */
    public StandardDescription getStandardDescription() {
        return standardDescription;
    }

    /**
     * Sets the value of the standardDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardDescription }
     *     
     */
    public void setStandardDescription(StandardDescription value) {
        this.standardDescription = value;
    }

    /**
     * Gets the value of the qc property.
     * 
     * @return
     *     possible object is
     *     {@link Qc }
     *     
     */
    public Qc getQc() {
        return qc;
    }

    /**
     * Sets the value of the qc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qc }
     *     
     */
    public void setQc(Qc value) {
        this.qc = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeight(BigDecimal value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWidth(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }
    
    /**
     * Gets the value of the qualityProportion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityProportion() {
        return qualityProportion;
    }

    /**
     * Sets the value of the qualityProportion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityProportion(String value) {
        this.qualityProportion = value;
    }


    /**
     * Gets the value of the isPresent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPresent() {
        return isPresent;
    }

    /**
     * Sets the value of the isPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPresent(String value) {
        this.isPresent = value;
    }

    /**
     * Gets the value of the isVirtualProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsVirtualProduct() {
        return isVirtualProduct;
    }

    /**
     * Sets the value of the isVirtualProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsVirtualProduct(String value) {
        this.isVirtualProduct = value;
    }

    /**
     * Gets the value of the transportProperty property.
     * 
     */
    public String getTransportProperty() {
        return transportProperty;
    }

    /**
     * Sets the value of the transportProperty property.
     * 
     */
    public void setTransportProperty(String value) {
        this.transportProperty = value;
    }

    /**
     * Gets the value of the isFragile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFragile() {
        return isFragile;
    }

    /**
     * Sets the value of the isFragile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFragile(String value) {
        this.isFragile = value;
    }
    
    /**
     * Gets the value of the itemClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemClass() {
        return itemClass;
    }

    /**
     * Sets the value of the itemClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemClass(String value) {
        this.itemClass = value;
    }

    /**
     * Gets the value of the itemStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemStyle() {
        return itemStyle;
    }

    /**
     * Sets the value of the itemStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemStyle(String value) {
        this.itemStyle = value;
    }

    /**
     * Gets the value of the itemColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemColor() {
        return itemColor;
    }

    /**
     * Sets the value of the itemColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemColor(String value) {
        this.itemColor = value;
    }

    /**
     * Gets the value of the itemSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemSize() {
        return itemSize;
    }

    /**
     * Sets the value of the itemSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemSize(String value) {
        this.itemSize = value;
    }

    /**
     * Gets the value of the storageTemperature property.
     * 
     */
    public int getStorageTemperature() {
        return storageTemperature;
    }

    /**
     * Sets the value of the storageTemperature property.
     * 
     */
    public void setStorageTemperature(int value) {
        this.storageTemperature = value;
    }

    /**
     * Gets the value of the transportTemperature property.
     * 
     */
    public int getTransportTemperature() {
        return transportTemperature;
    }

    /**
     * Sets the value of the transportTemperature property.
     * 
     */
    public void setTransportTemperature(int value) {
        this.transportTemperature = value;
    }
    
    /**
     * Gets the value of the expirationDateDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDateDays() {
        return expirationDateDays;
    }

    /**
     * Sets the value of the expirationDateDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDateDays(String value) {
        this.expirationDateDays = value;
    }

    /**
     * Gets the value of the shelfLife property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShelfLife() {
        return shelfLife;
    }

    /**
     * Sets the value of the shelfLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShelfLife(String value) {
        this.shelfLife = value;
    }

    /**
     * Gets the value of the qtymin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtymin() {
        return qtymin;
    }

    /**
     * Sets the value of the qtymin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtymin(String value) {
        this.qtymin = value;
    }

    /**
     * Gets the value of the lotTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link LotTemplate }
     *     
     */
    public LotTemplate getLotTemplate() {
        return lotTemplate;
    }

    /**
     * Sets the value of the lotTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotTemplate }
     *     
     */
    public void setLotTemplate(LotTemplate value) {
        this.lotTemplate = value;
    }

    /**
     * Gets the value of the serialNumTrackInbound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumTrackInbound() {
        return serialNumTrackInbound;
    }

    /**
     * Sets the value of the serialNumTrackInbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumTrackInbound(String value) {
        this.serialNumTrackInbound = value;
    }

    /**
     * Gets the value of the serialNumTrackOutbound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumTrackOutbound() {
        return serialNumTrackOutbound;
    }

    /**
     * Sets the value of the serialNumTrackOutbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumTrackOutbound(String value) {
        this.serialNumTrackOutbound = value;
    }
    
    /**
     * Gets the value of the serialNumTrackInventory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumTrackInventory() {
        return serialNumTrackInventory;
    }

    /**
     * Sets the value of the serialNumTrackInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumTrackInventory(String value) {
        this.serialNumTrackInventory = value;
    }

    /**
     * Gets the value of the bomAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBomAction() {
        return bomAction;
    }

    /**
     * Sets the value of the bomAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBomAction(String value) {
        this.bomAction = value;
    }

    /**
     * Gets the value of the itemClassify1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemClassify1() {
        return itemClassify1;
    }

    /**
     * Sets the value of the itemClassify1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemClassify1(String value) {
        this.itemClassify1 = value;
    }

    /**
     * Gets the value of the itemClassify2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemClassify2() {
        return itemClassify2;
    }

    /**
     * Sets the value of the itemClassify2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemClassify2(String value) {
        this.itemClassify2 = value;
    }

    /**
     * Gets the value of the itemClassify3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemClassify3() {
        return itemClassify3;
    }

    /**
     * Sets the value of the itemClassify3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemClassify3(String value) {
        this.itemClassify3 = value;
    }

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return
     *     possible object is
     *     {@link SkuReqBarCode }
     *     
     */
    public SkuReqBarCode getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuReqBarCode }
     *     
     */
    public void setBarCode(SkuReqBarCode value) {
        this.barCode = value;
    }

    /**
     * Gets the value of the itemCategory property.
     * 
     * @return
     *     possible object is
     *     {@link SkuReqItemCategory }
     *     
     */
    public SkuReqItemCategory getItemCategory() {
        return itemCategory;
    }

    /**
     * Sets the value of the itemCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuReqItemCategory }
     *     
     */
    public void setItemCategory(SkuReqItemCategory value) {
        this.itemCategory = value;
    }

    /**
     * Gets the value of the containers property.
     * 
     * @return
     *     possible object is
     *     {@link Containers }
     *     
     */
    public Containers getContainers() {
        return containers;
    }

    /**
     * Sets the value of the containers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Containers }
     *     
     */
    public void setContainers(Containers value) {
        this.containers = value;
    }

}
