//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 06:35:51 ���� CST 
//


package com.jumbo.webservice.sf.tw.sku.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BarCode1"/>
 *         &lt;element ref="{}BarCode2"/>
 *         &lt;element ref="{}BarCode3"/>
 *         &lt;element ref="{}BarCode4"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "barCode1",
    "barCode2",
    "barCode3",
    "barCode4"
})
@XmlRootElement(name = "BarCode")
public class SkuReqBarCode {

    @XmlElement(name = "BarCode1", required = false)
    protected String barCode1;
    @XmlElement(name = "BarCode2", required = false)
    protected String barCode2;
    @XmlElement(name = "BarCode3", required = false)
    protected String barCode3;
    @XmlElement(name = "BarCode4", required = false)
    protected String barCode4;

    /**
     * Gets the value of the barCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode1() {
        return barCode1;
    }

    /**
     * Sets the value of the barCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode1(String value) {
        this.barCode1 = value;
    }

    /**
     * Gets the value of the barCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode2() {
        return barCode2;
    }

    /**
     * Sets the value of the barCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode2(String value) {
        this.barCode2 = value;
    }

    /**
     * Gets the value of the barCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode3() {
        return barCode3;
    }

    /**
     * Sets the value of the barCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode3(String value) {
        this.barCode3 = value;
    }

    /**
     * Gets the value of the barCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode4() {
        return barCode4;
    }

    /**
     * Sets the value of the barCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode4(String value) {
        this.barCode4 = value;
    }

}
